//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.24 at 08:20:02 PM MSK 
//


package ru.homyakin.zakupki.models._223fz.detachedrights;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Данные о правах для перечня ИПВП
 * 
 * <p>Java class for listInnovRightsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listInnovRightsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="listInnovCreate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="listInnovModification" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="listInnovView" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listInnovRightsType", propOrder = {
    "listInnovCreate",
    "listInnovModification",
    "listInnovView"
})
public class ListInnovRightsType {

    protected Boolean listInnovCreate;
    protected Boolean listInnovModification;
    protected Boolean listInnovView;

    /**
     * Gets the value of the listInnovCreate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isListInnovCreate() {
        return listInnovCreate;
    }

    /**
     * Sets the value of the listInnovCreate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setListInnovCreate(Boolean value) {
        this.listInnovCreate = value;
    }

    /**
     * Gets the value of the listInnovModification property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isListInnovModification() {
        return listInnovModification;
    }

    /**
     * Sets the value of the listInnovModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setListInnovModification(Boolean value) {
        this.listInnovModification = value;
    }

    /**
     * Gets the value of the listInnovView property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isListInnovView() {
        return listInnovView;
    }

    /**
     * Sets the value of the listInnovView property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setListInnovView(Boolean value) {
        this.listInnovView = value;
    }

}
