//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.24 at 08:20:14 PM MSK 
//


package ru.homyakin.zakupki.models._223fz.orderclauselist;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.homyakin.zakupki.models._223fz.orderclauselist package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.homyakin.zakupki.models._223fz.orderclauselist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderClause }
     * 
     */
    public OrderClause createOrderClause() {
        return new OrderClause();
    }

    /**
     * Create an instance of {@link OrderClauseDataType }
     * 
     */
    public OrderClauseDataType createOrderClauseDataType() {
        return new OrderClauseDataType();
    }

    /**
     * Create an instance of {@link OrderClause.Body }
     * 
     */
    public OrderClause.Body createOrderClauseBody() {
        return new OrderClause.Body();
    }

    /**
     * Create an instance of {@link OrderClauseItemType }
     * 
     */
    public OrderClauseItemType createOrderClauseItemType() {
        return new OrderClauseItemType();
    }

    /**
     * Create an instance of {@link PurchaseMethodType }
     * 
     */
    public PurchaseMethodType createPurchaseMethodType() {
        return new PurchaseMethodType();
    }

    /**
     * Create an instance of {@link OrderClauseDataType.TemplateStructure }
     * 
     */
    public OrderClauseDataType.TemplateStructure createOrderClauseDataTypeTemplateStructure() {
        return new OrderClauseDataType.TemplateStructure();
    }

    /**
     * Create an instance of {@link OrderClauseDataType.TypalOrderInfo }
     * 
     */
    public OrderClauseDataType.TypalOrderInfo createOrderClauseDataTypeTypalOrderInfo() {
        return new OrderClauseDataType.TypalOrderInfo();
    }

}
