//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.24 at 08:20:15 PM MSK 
//


package ru.homyakin.zakupki.models._223fz.complaint;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.homyakin.zakupki.models._223fz.complaint package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.homyakin.zakupki.models._223fz.complaint
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComplaintVerificationPlan }
     * 
     */
    public ComplaintVerificationPlan createComplaintVerificationPlan() {
        return new ComplaintVerificationPlan();
    }

    /**
     * Create an instance of {@link ComplaintVerificationResult }
     * 
     */
    public ComplaintVerificationResult createComplaintVerificationResult() {
        return new ComplaintVerificationResult();
    }

    /**
     * Create an instance of {@link Complaint }
     * 
     */
    public Complaint createComplaint() {
        return new Complaint();
    }

    /**
     * Create an instance of {@link ComplaintDecision }
     * 
     */
    public ComplaintDecision createComplaintDecision() {
        return new ComplaintDecision();
    }

    /**
     * Create an instance of {@link ComplaintWithdraw }
     * 
     */
    public ComplaintWithdraw createComplaintWithdraw() {
        return new ComplaintWithdraw();
    }

    /**
     * Create an instance of {@link ComplaintPlacerType }
     * 
     */
    public ComplaintPlacerType createComplaintPlacerType() {
        return new ComplaintPlacerType();
    }

    /**
     * Create an instance of {@link ComplaintVerificationPlan.Body }
     * 
     */
    public ComplaintVerificationPlan.Body createComplaintVerificationPlanBody() {
        return new ComplaintVerificationPlan.Body();
    }

    /**
     * Create an instance of {@link ComplaintVerificationResult.Body }
     * 
     */
    public ComplaintVerificationResult.Body createComplaintVerificationResultBody() {
        return new ComplaintVerificationResult.Body();
    }

    /**
     * Create an instance of {@link Complaint.Body }
     * 
     */
    public Complaint.Body createComplaintBody() {
        return new Complaint.Body();
    }

    /**
     * Create an instance of {@link ComplaintDecision.Body }
     * 
     */
    public ComplaintDecision.Body createComplaintDecisionBody() {
        return new ComplaintDecision.Body();
    }

    /**
     * Create an instance of {@link ComplaintWithdraw.Body }
     * 
     */
    public ComplaintWithdraw.Body createComplaintWithdrawBody() {
        return new ComplaintWithdraw.Body();
    }

    /**
     * Create an instance of {@link PrescriptionType }
     * 
     */
    public PrescriptionType createPrescriptionType() {
        return new PrescriptionType();
    }

    /**
     * Create an instance of {@link ComplaintDecisionItemType }
     * 
     */
    public ComplaintDecisionItemType createComplaintDecisionItemType() {
        return new ComplaintDecisionItemType();
    }

    /**
     * Create an instance of {@link ComplaintDecisionDataType }
     * 
     */
    public ComplaintDecisionDataType createComplaintDecisionDataType() {
        return new ComplaintDecisionDataType();
    }

    /**
     * Create an instance of {@link ComplaintVerificationPlanDataType }
     * 
     */
    public ComplaintVerificationPlanDataType createComplaintVerificationPlanDataType() {
        return new ComplaintVerificationPlanDataType();
    }

    /**
     * Create an instance of {@link ComplaintVerificationCustomerListType }
     * 
     */
    public ComplaintVerificationCustomerListType createComplaintVerificationCustomerListType() {
        return new ComplaintVerificationCustomerListType();
    }

    /**
     * Create an instance of {@link ComplaintWithdrawItemType }
     * 
     */
    public ComplaintWithdrawItemType createComplaintWithdrawItemType() {
        return new ComplaintWithdrawItemType();
    }

    /**
     * Create an instance of {@link ComplaintDataType }
     * 
     */
    public ComplaintDataType createComplaintDataType() {
        return new ComplaintDataType();
    }

    /**
     * Create an instance of {@link ComplaintVerificationResultItemType }
     * 
     */
    public ComplaintVerificationResultItemType createComplaintVerificationResultItemType() {
        return new ComplaintVerificationResultItemType();
    }

    /**
     * Create an instance of {@link ComplaintVerificationResultDataType }
     * 
     */
    public ComplaintVerificationResultDataType createComplaintVerificationResultDataType() {
        return new ComplaintVerificationResultDataType();
    }

    /**
     * Create an instance of {@link ComplaintVerificationPlanItemType }
     * 
     */
    public ComplaintVerificationPlanItemType createComplaintVerificationPlanItemType() {
        return new ComplaintVerificationPlanItemType();
    }

    /**
     * Create an instance of {@link ComplaintItemType }
     * 
     */
    public ComplaintItemType createComplaintItemType() {
        return new ComplaintItemType();
    }

    /**
     * Create an instance of {@link ComplaintWithdrawDataType }
     * 
     */
    public ComplaintWithdrawDataType createComplaintWithdrawDataType() {
        return new ComplaintWithdrawDataType();
    }

    /**
     * Create an instance of {@link ComplaintPlacerType.LegalPerson }
     * 
     */
    public ComplaintPlacerType.LegalPerson createComplaintPlacerTypeLegalPerson() {
        return new ComplaintPlacerType.LegalPerson();
    }

    /**
     * Create an instance of {@link ComplaintPlacerType.IndividualPerson }
     * 
     */
    public ComplaintPlacerType.IndividualPerson createComplaintPlacerTypeIndividualPerson() {
        return new ComplaintPlacerType.IndividualPerson();
    }

}
