//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.05 at 11:35:44 PM MSK 
//


package ru.homyakin.zakupki.models._223fz.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Информация о плане и позиции
 * 
 * <p>Java class for planInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="planInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="planRegistrationNumber" type="{http://zakupki.gov.ru/223fz/types/1}registrationNumberType" minOccurs="0"/>
 *         &lt;element name="planGuid" type="{http://zakupki.gov.ru/223fz/types/1}guidType"/>
 *         &lt;element name="positionNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="lotPlanPosition" type="{http://zakupki.gov.ru/223fz/types/1}lotPlanPositionType"/>
 *         &lt;element name="positionGuid" type="{http://zakupki.gov.ru/223fz/types/1}guidType"/>
 *         &lt;element name="contractSubject" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "planInfoType", propOrder = {
    "planRegistrationNumber",
    "planGuid",
    "positionNumber",
    "lotPlanPosition",
    "positionGuid",
    "contractSubject"
})
public class PlanInfoType {

    protected String planRegistrationNumber;
    @XmlElement(required = true)
    protected String planGuid;
    protected long positionNumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LotPlanPositionType lotPlanPosition;
    @XmlElement(required = true)
    protected String positionGuid;
    protected String contractSubject;

    /**
     * Gets the value of the planRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanRegistrationNumber() {
        return planRegistrationNumber;
    }

    /**
     * Sets the value of the planRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanRegistrationNumber(String value) {
        this.planRegistrationNumber = value;
    }

    /**
     * Gets the value of the planGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanGuid() {
        return planGuid;
    }

    /**
     * Sets the value of the planGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanGuid(String value) {
        this.planGuid = value;
    }

    /**
     * Gets the value of the positionNumber property.
     * 
     */
    public long getPositionNumber() {
        return positionNumber;
    }

    /**
     * Sets the value of the positionNumber property.
     * 
     */
    public void setPositionNumber(long value) {
        this.positionNumber = value;
    }

    /**
     * Gets the value of the lotPlanPosition property.
     * 
     * @return
     *     possible object is
     *     {@link LotPlanPositionType }
     *     
     */
    public LotPlanPositionType getLotPlanPosition() {
        return lotPlanPosition;
    }

    /**
     * Sets the value of the lotPlanPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link LotPlanPositionType }
     *     
     */
    public void setLotPlanPosition(LotPlanPositionType value) {
        this.lotPlanPosition = value;
    }

    /**
     * Gets the value of the positionGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionGuid() {
        return positionGuid;
    }

    /**
     * Sets the value of the positionGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionGuid(String value) {
        this.positionGuid = value;
    }

    /**
     * Gets the value of the contractSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractSubject() {
        return contractSubject;
    }

    /**
     * Sets the value of the contractSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractSubject(String value) {
        this.contractSubject = value;
    }

}
