//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.07 at 02:09:47 PM MSK 
//


package ru.homyakin.zakupki.documentsinfo._223fz.purchase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ru.homyakin.zakupki.documentsinfo._223fz.types.ItemType;


/**
 * Данные позиции в пакете
 * 
 * <p>Java class for purchaseProtocolRZ2AE94FZItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="purchaseProtocolRZ2AE94FZItemType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://zakupki.gov.ru/223fz/types/1}itemType">
 *       &lt;sequence>
 *         &lt;element name="purchaseProtocolRZ2AE94FZData" type="{http://zakupki.gov.ru/223fz/purchase/1}purchaseProtocolRZ2AE94FZDataType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purchaseProtocolRZ2AE94FZItemType", propOrder = {
    "purchaseProtocolRZ2AE94FZData"
})
public class PurchaseProtocolRZ2AE94FZItemType
    extends ItemType
{

    @XmlElement(required = true)
    protected PurchaseProtocolRZ2AE94FZDataType purchaseProtocolRZ2AE94FZData;

    /**
     * Gets the value of the purchaseProtocolRZ2AE94FZData property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseProtocolRZ2AE94FZDataType }
     *     
     */
    public PurchaseProtocolRZ2AE94FZDataType getPurchaseProtocolRZ2AE94FZData() {
        return purchaseProtocolRZ2AE94FZData;
    }

    /**
     * Sets the value of the purchaseProtocolRZ2AE94FZData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseProtocolRZ2AE94FZDataType }
     *     
     */
    public void setPurchaseProtocolRZ2AE94FZData(PurchaseProtocolRZ2AE94FZDataType value) {
        this.purchaseProtocolRZ2AE94FZData = value;
    }

}
