//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.24 at 08:20:08 PM MSK 
//


package ru.homyakin.zakupki.models._223fz.purchase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.homyakin.zakupki.models._223fz.types.ElectronicPlaceInfoType;


/**
 * Извещение о закупке "Аукцион в электронной форме (по 94ФЗ)"
 * 
 * <p>Java class for purchaseNoticeAE94FZDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="purchaseNoticeAE94FZDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://zakupki.gov.ru/223fz/purchase/1}purchaseNoticeNonISBaseType">
 *       &lt;sequence>
 *         &lt;element name="electronicPlaceInfo" type="{http://zakupki.gov.ru/223fz/types/1}electronicPlaceInfoType"/>
 *         &lt;element name="auctionTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="applExamPlace" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="applExamPeriodTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="submissionCloseDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="publicationPlannedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="considerationSecondPartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="summingupPlace" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="summingupDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purchaseNoticeAE94FZDataType", propOrder = {
    "electronicPlaceInfo",
    "auctionTime",
    "applExamPlace",
    "applExamPeriodTime",
    "submissionCloseDateTime",
    "publicationPlannedDate",
    "considerationSecondPartDate",
    "summingupPlace",
    "summingupDate"
})
public class PurchaseNoticeAE94FZDataType
    extends PurchaseNoticeNonISBaseType
{

    @XmlElement(required = true)
    protected ElectronicPlaceInfoType electronicPlaceInfo;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar auctionTime;
    protected String applExamPlace;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar applExamPeriodTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar submissionCloseDateTime;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar publicationPlannedDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar considerationSecondPartDate;
    protected String summingupPlace;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar summingupDate;

    /**
     * Gets the value of the electronicPlaceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ElectronicPlaceInfoType }
     *     
     */
    public ElectronicPlaceInfoType getElectronicPlaceInfo() {
        return electronicPlaceInfo;
    }

    /**
     * Sets the value of the electronicPlaceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectronicPlaceInfoType }
     *     
     */
    public void setElectronicPlaceInfo(ElectronicPlaceInfoType value) {
        this.electronicPlaceInfo = value;
    }

    /**
     * Gets the value of the auctionTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAuctionTime() {
        return auctionTime;
    }

    /**
     * Sets the value of the auctionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAuctionTime(XMLGregorianCalendar value) {
        this.auctionTime = value;
    }

    /**
     * Gets the value of the applExamPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplExamPlace() {
        return applExamPlace;
    }

    /**
     * Sets the value of the applExamPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplExamPlace(String value) {
        this.applExamPlace = value;
    }

    /**
     * Gets the value of the applExamPeriodTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApplExamPeriodTime() {
        return applExamPeriodTime;
    }

    /**
     * Sets the value of the applExamPeriodTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApplExamPeriodTime(XMLGregorianCalendar value) {
        this.applExamPeriodTime = value;
    }

    /**
     * Gets the value of the submissionCloseDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionCloseDateTime() {
        return submissionCloseDateTime;
    }

    /**
     * Sets the value of the submissionCloseDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionCloseDateTime(XMLGregorianCalendar value) {
        this.submissionCloseDateTime = value;
    }

    /**
     * Gets the value of the publicationPlannedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublicationPlannedDate() {
        return publicationPlannedDate;
    }

    /**
     * Sets the value of the publicationPlannedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublicationPlannedDate(XMLGregorianCalendar value) {
        this.publicationPlannedDate = value;
    }

    /**
     * Gets the value of the considerationSecondPartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getConsiderationSecondPartDate() {
        return considerationSecondPartDate;
    }

    /**
     * Sets the value of the considerationSecondPartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setConsiderationSecondPartDate(XMLGregorianCalendar value) {
        this.considerationSecondPartDate = value;
    }

    /**
     * Gets the value of the summingupPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummingupPlace() {
        return summingupPlace;
    }

    /**
     * Sets the value of the summingupPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummingupPlace(String value) {
        this.summingupPlace = value;
    }

    /**
     * Gets the value of the summingupDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSummingupDate() {
        return summingupDate;
    }

    /**
     * Sets the value of the summingupDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSummingupDate(XMLGregorianCalendar value) {
        this.summingupDate = value;
    }

}
