//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.24 at 08:20:08 PM MSK 
//


package ru.homyakin.zakupki.models._223fz.purchase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Извещение о закупке "Конкурс в электронной форме, участниками которого могут являться только субъекты малого и среднего предпринимательства"
 * 
 * <p>Java class for purchaseNoticeKESMBODataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="purchaseNoticeKESMBODataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://zakupki.gov.ru/223fz/purchase/1}purchaseNoticeESMBODataType">
 *       &lt;sequence>
 *         &lt;element name="emPlacementDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="emNoticeUrl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="3000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="envelopeOpeningTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purchaseNoticeKESMBODataType", propOrder = {
    "emPlacementDate",
    "emNoticeUrl",
    "envelopeOpeningTime"
})
public class PurchaseNoticeKESMBODataType
    extends PurchaseNoticeESMBODataType
{

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar emPlacementDate;
    protected String emNoticeUrl;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar envelopeOpeningTime;

    /**
     * Gets the value of the emPlacementDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEmPlacementDate() {
        return emPlacementDate;
    }

    /**
     * Sets the value of the emPlacementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEmPlacementDate(XMLGregorianCalendar value) {
        this.emPlacementDate = value;
    }

    /**
     * Gets the value of the emNoticeUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmNoticeUrl() {
        return emNoticeUrl;
    }

    /**
     * Sets the value of the emNoticeUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmNoticeUrl(String value) {
        this.emNoticeUrl = value;
    }

    /**
     * Gets the value of the envelopeOpeningTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEnvelopeOpeningTime() {
        return envelopeOpeningTime;
    }

    /**
     * Sets the value of the envelopeOpeningTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEnvelopeOpeningTime(XMLGregorianCalendar value) {
        this.envelopeOpeningTime = value;
    }

}
