-- MySQL Script generated by MySQL Workbench
-- Вс 31 мая 2020 20:29:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zakupki
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zakupki
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zakupki` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `zakupki`;

-- -----------------------------------------------------
-- Table `zakupki`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`currency`
(
    `code`         VARCHAR(3)  NOT NULL,
    `digital_code` VARCHAR(3)  NOT NULL,
    `name`         VARCHAR(50) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`okato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`okato`
(
    `code` VARCHAR(11)  NOT NULL,
    `name` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`okopf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`okopf`
(
    `code` VARCHAR(5)   NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`customer`
(
    `inn`                           VARCHAR(12)   NOT NULL,
    `full_name`                     VARCHAR(1000) NULL DEFAULT NULL,
    `short_name`                    VARCHAR(500)  NULL DEFAULT NULL,
    `iko`                           VARCHAR(22)   NULL DEFAULT NULL,
    `kpp`                           VARCHAR(9)    NOT NULL,
    `ogrn`                          VARCHAR(13)   NOT NULL,
    `legal_address`                 VARCHAR(2000) NULL DEFAULT NULL,
    `postal_address`                VARCHAR(2000) NULL DEFAULT NULL,
    `phone`                         VARCHAR(300)  NULL DEFAULT NULL,
    `fax`                           VARCHAR(300)  NULL DEFAULT NULL,
    `email`                         VARCHAR(300)  NULL DEFAULT NULL,
    `okato`                         VARCHAR(11)   NULL DEFAULT NULL,
    `okopf_code`                    VARCHAR(5)    NULL DEFAULT NULL,
    `okpo`                          VARCHAR(8)    NULL DEFAULT NULL,
    `customer_registration_date`    DATETIME      NULL DEFAULT NULL,
    `timezone_offset`               INT           NULL DEFAULT NULL,
    `timezone_name`                 VARCHAR(100)  NULL DEFAULT NULL,
    `region`                        VARCHAR(200)  NULL DEFAULT NULL,
    `customer_assessed_compliance`  TINYINT(1)    NULL DEFAULT NULL,
    `customer_monitored_compliance` TINYINT(1)    NULL DEFAULT NULL,
    PRIMARY KEY (`inn`),
    INDEX `organization_okopf_code_foreign` (`okopf_code` ASC) VISIBLE,
    INDEX `customer_okato_foreign` (`okato` ASC) VISIBLE,
    CONSTRAINT `customer_okato_foreign`
        FOREIGN KEY (`okato`)
            REFERENCES `zakupki`.`okato` (`code`),
    CONSTRAINT `organization_okopf_code_foreign`
        FOREIGN KEY (`okopf_code`)
            REFERENCES `zakupki`.`okopf` (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_category`
(
    `code`        INT           NOT NULL,
    `description` VARCHAR(1100) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`plan_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`plan_status`
(
    `code` VARCHAR(1)  NOT NULL,
    `name` VARCHAR(35) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_plan`
(
    `guid`                                          VARCHAR(36)    NOT NULL,
    `customer_inn`                                  VARCHAR(12)    NULL DEFAULT NULL,
    `placer_inn`                                    VARCHAR(12)    NOT NULL,
    `plan_type`                                     VARCHAR(10)    NULL DEFAULT NULL,
    `is_upload_complete`                            TINYINT(1)     NULL DEFAULT NULL,
    `create_date_time`                              DATETIME       NULL DEFAULT NULL,
    `url_eis`                                       VARCHAR(3000)  NULL DEFAULT NULL,
    `url_vsrz`                                      VARCHAR(3000)  NULL DEFAULT NULL,
    `url_kis_rmis`                                  VARCHAR(3000)  NULL DEFAULT NULL,
    `registration_number`                           BIGINT         NULL DEFAULT NULL,
    `name`                                          VARCHAR(2000)  NULL DEFAULT NULL,
    `additional_info`                               VARCHAR(2000)  NULL DEFAULT NULL,
    `start_date`                                    DATE           NOT NULL,
    `end_date`                                      DATE           NOT NULL,
    `approve_date`                                  DATE           NOT NULL,
    `publication_date_time`                         DATETIME       NULL DEFAULT NULL,
    `is_digit_form`                                 TINYINT(1)     NULL DEFAULT NULL,
    `summ_size_ch15`                                TINYINT(1)     NULL DEFAULT NULL,
    `is_imported_from_vsrz`                         TINYINT(1)     NULL DEFAULT NULL,
    `status_code`                                   VARCHAR(1)     NULL DEFAULT NULL,
    `version`                                       INT            NULL DEFAULT NULL,
    `modification_description`                      VARCHAR(2000)  NULL DEFAULT NULL,
    `use_new_classifiers`                           TINYINT(1)     NULL DEFAULT NULL,
    `exclude_volume`                                DECIMAL(22, 2) NULL DEFAULT NULL,
    `volume_smb`                                    DECIMAL(22, 2) NULL DEFAULT NULL,
    `annual_volume`                                 DECIMAL(22, 2) NULL DEFAULT NULL,
    `percent_smb`                                   INT            NULL DEFAULT NULL,
    `smb_partition_changed`                         TINYINT(1)     NULL DEFAULT NULL,
    `annual_volume_smb_less_18_percent`             TINYINT(1)     NULL DEFAULT NULL,
    `reporting_year`                                INT            NOT NULL,
    `previous_year_annual_volume`                   DECIMAL(22, 2) NULL DEFAULT NULL,
    `previous_year_annual_volume_hitech`            DECIMAL(22, 2) NULL DEFAULT NULL,
    `previous_year_annual_volume_hitech_smb`        DECIMAL(22, 2) NULL DEFAULT NULL,
    `annual_year_annual_volume_hitech_summ`         DECIMAL(22, 2) NULL DEFAULT NULL,
    `annual_year_annual_volume_hitech_increase`     DECIMAL(22, 2) NULL DEFAULT NULL,
    `annual_year_annual_volume_hitech_percent`      DECIMAL(22, 2) NULL DEFAULT NULL,
    `annual_year_annual_volume_hitech_smb_summ`     DECIMAL(22, 2) NULL DEFAULT NULL,
    `annual_year_annual_volume_hitech_smb_increase` DECIMAL(22, 2) NULL DEFAULT NULL,
    `annual_year_annual_volume_hitech_smb_percent`  DECIMAL(22, 2) NULL DEFAULT NULL,
    PRIMARY KEY (`guid`),
    INDEX `purchase_plan_placer_inn_foreign` (`placer_inn` ASC) VISIBLE,
    INDEX `purchase_plan_status_code_foreign` (`status_code` ASC) VISIBLE,
    INDEX `purchase_plan_customer_inn_foreign` (`customer_inn` ASC) VISIBLE,
    CONSTRAINT `purchase_plan_customer_inn_foreign`
        FOREIGN KEY (`customer_inn`)
            REFERENCES `zakupki`.`customer` (`inn`),
    CONSTRAINT `purchase_plan_placer_inn_foreign`
        FOREIGN KEY (`placer_inn`)
            REFERENCES `zakupki`.`customer` (`inn`),
    CONSTRAINT `purchase_plan_status_code_foreign`
        FOREIGN KEY (`status_code`)
            REFERENCES `zakupki`.`plan_status` (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`plan_item_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`plan_item_status`
(
    `code` VARCHAR(1)  NOT NULL,
    `name` VARCHAR(15) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`plan_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`plan_item`
(
    `guid`                          VARCHAR(36)    NOT NULL,
    `purchase_plan_guid`            VARCHAR(36)    NOT NULL,
    `ordinal_number`                INT            NOT NULL,
    `contract_subject`              VARCHAR(2000)  NOT NULL,
    `plan_item_customer_inn`        VARCHAR(12)    NOT NULL,
    `minimum_requirements`          VARCHAR(2000)  NULL DEFAULT NULL,
    `contract_end_date`             DATE           NOT NULL,
    `additional_info`               VARCHAR(1000)  NULL DEFAULT NULL,
    `modification_description`      VARCHAR(2000)  NULL DEFAULT NULL,
    `status_code`                   VARCHAR(1)     NULL DEFAULT NULL,
    `is_purchase_placed`            TINYINT(1)     NULL DEFAULT NULL,
    `changed_gws_and_dates`         TINYINT(1)     NULL DEFAULT NULL,
    `changed_nmsk_more_ten_percent` TINYINT(1)     NULL DEFAULT NULL,
    `other_changes`                 TINYINT(1)     NULL DEFAULT NULL,
    `check_result`                  VARCHAR(8)     NULL DEFAULT NULL,
    `error_messages`                VARCHAR(4000)  NULL DEFAULT NULL,
    `cancellation_reason`           VARCHAR(14)    NULL DEFAULT NULL,
    `long_term`                     TINYINT(1)     NULL DEFAULT NULL,
    `shared`                        TINYINT(1)     NULL DEFAULT NULL,
    `initial_position_guid`         VARCHAR(36)    NULL DEFAULT NULL,
    `initial_plan_guid`             VARCHAR(36)    NULL DEFAULT NULL,
    `maximum_contract_price`        DECIMAL(22, 2) NULL DEFAULT NULL,
    `currency_code`                 VARCHAR(3)     NULL DEFAULT NULL,
    `exchange_rate`                 DECIMAL(16, 6) NULL DEFAULT NULL,
    `exchange_rate_date`            DATE           NULL DEFAULT NULL,
    `maximum_contract_price_rub`    DECIMAL(22, 2) NULL DEFAULT NULL,
    `order_pricing`                 VARCHAR(2000)  NULL DEFAULT NULL,
    `innovation_equivalent`         TINYINT(1)     NULL DEFAULT NULL,
    `purchase_category_code`        INT            NULL DEFAULT NULL,
    `is_smb`                        TINYINT(1)     NOT NULL,
    `is_innovation`                 TINYINT(1)     NOT NULL,
    PRIMARY KEY (`guid`),
    INDEX `plan_item_purchase_plan_guid_foreign` (`purchase_plan_guid` ASC) VISIBLE,
    INDEX `plan_item_plan_item_customer_inn_foreign` (`plan_item_customer_inn` ASC) VISIBLE,
    INDEX `plan_item_status_code_foreign` (`status_code` ASC) VISIBLE,
    INDEX `plan_item_purchase_category_code_foreign` (`purchase_category_code` ASC) VISIBLE,
    INDEX `plan_item_currency_code_foreign` (`currency_code` ASC) VISIBLE,
    CONSTRAINT `plan_item_currency_code_foreign`
        FOREIGN KEY (`currency_code`)
            REFERENCES `zakupki`.`currency` (`code`),
    CONSTRAINT `plan_item_plan_item_customer_inn_foreign`
        FOREIGN KEY (`plan_item_customer_inn`)
            REFERENCES `zakupki`.`customer` (`inn`),
    CONSTRAINT `plan_item_purchase_category_code_foreign`
        FOREIGN KEY (`purchase_category_code`)
            REFERENCES `zakupki`.`purchase_category` (`code`),
    CONSTRAINT `plan_item_purchase_plan_guid_foreign`
        FOREIGN KEY (`purchase_plan_guid`)
            REFERENCES `zakupki`.`purchase_plan` (`guid`),
    CONSTRAINT `plan_item_status_code_foreign`
        FOREIGN KEY (`status_code`)
            REFERENCES `zakupki`.`plan_item_status` (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`innovation_plan_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`innovation_plan_item`
(
    `guid`                 VARCHAR(36) NOT NULL,
    `ignored_purchase`     TINYINT(1)  NULL DEFAULT NULL,
    `purchase_period_year` INT         NOT NULL,
    PRIMARY KEY (`guid`),
    CONSTRAINT `innovation_plan_item_guid_foreign`
        FOREIGN KEY (`guid`)
            REFERENCES `zakupki`.`plan_item` (`guid`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`okdp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`okdp`
(
    `code` VARCHAR(20)  NOT NULL,
    `name` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`okpd2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`okpd2`
(
    `code` VARCHAR(20)  NOT NULL,
    `name` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`okved2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`okved2`
(
    `code` VARCHAR(20)  NOT NULL,
    `name` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`okved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`okved`
(
    `code` VARCHAR(20)  NOT NULL,
    `name` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`innovation_plan_item_row`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`innovation_plan_item_row`
(
    `plan_item_guid`  VARCHAR(36)   NOT NULL,
    `ordinal_number`  INT           NOT NULL,
    `additional_info` VARCHAR(2000) NULL DEFAULT NULL,
    `okdp_code`       VARCHAR(20)   NULL DEFAULT NULL,
    `okdp_name`       VARCHAR(550)  NULL DEFAULT NULL,
    `okpd2_code`      VARCHAR(20)   NULL DEFAULT NULL,
    `okpd2_name`      VARCHAR(550)  NULL DEFAULT NULL,
    `okved_code`      VARCHAR(20)   NULL DEFAULT NULL,
    `okved_name`      VARCHAR(550)  NULL DEFAULT NULL,
    `okved2_code`     VARCHAR(20)   NULL DEFAULT NULL,
    `okved2_name`     VARCHAR(550)  NULL DEFAULT NULL,
    PRIMARY KEY (`plan_item_guid`, `ordinal_number`),
    INDEX `innovation_plan_row_item_okdp_code_foreign` (`okdp_code` ASC) VISIBLE,
    INDEX `innovation_plan_row_item_okpd2_code_foreign` (`okpd2_code` ASC) VISIBLE,
    INDEX `innovation_plan_row_item_okved_code_foreign` (`okved_code` ASC) VISIBLE,
    INDEX `innovation_plan_row_item_okved2_code_foreign` (`okved2_code` ASC) VISIBLE,
    CONSTRAINT `innovation_plan_row_item_okdp_code_foreign`
        FOREIGN KEY (`okdp_code`)
            REFERENCES `zakupki`.`okdp` (`code`),
    CONSTRAINT `innovation_plan_row_item_okpd2_code_foreign`
        FOREIGN KEY (`okpd2_code`)
            REFERENCES `zakupki`.`okpd2` (`code`),
    CONSTRAINT `innovation_plan_row_item_okved2_code_foreign`
        FOREIGN KEY (`okved2_code`)
            REFERENCES `zakupki`.`okved2` (`code`),
    CONSTRAINT `innovation_plan_row_item_okved_code_foreign`
        FOREIGN KEY (`okved_code`)
            REFERENCES `zakupki`.`okved` (`code`),
    CONSTRAINT `innovation_plan_row_item_plan_item_guid_foreign`
        FOREIGN KEY (`plan_item_guid`)
            REFERENCES `zakupki`.`plan_item` (`guid`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`long_term_volumes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`long_term_volumes`
(
    `plan_item_guid`     VARCHAR(36)             NOT NULL,
    `is_smb`             TINYINT(1)              NOT NULL,
    `volume`             DECIMAL(22, 2) UNSIGNED NULL DEFAULT NULL,
    `volume_rub`         DECIMAL(22, 2)          NULL DEFAULT NULL,
    `currency_code`      VARCHAR(3)              NULL DEFAULT NULL,
    `exchange_rate`      DECIMAL(16, 6)          NULL DEFAULT NULL,
    `exchange_rate_date` DATE                    NULL DEFAULT NULL,
    PRIMARY KEY (`plan_item_guid`, `is_smb`),
    INDEX `long_term_volumes_currency_code_foreign` (`currency_code` ASC) VISIBLE,
    CONSTRAINT `long_term_volumes_currency_code_foreign`
        FOREIGN KEY (`currency_code`)
            REFERENCES `zakupki`.`currency` (`code`),
    CONSTRAINT `long_term_volumes_purchase_plan_item_guid_foreign`
        FOREIGN KEY (`plan_item_guid`)
            REFERENCES `zakupki`.`plan_item` (`guid`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`long_term_volume_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`long_term_volume_detail`
(
    `long_term_value_guid` VARCHAR(36)             NOT NULL,
    `year`                 INT                     NOT NULL,
    `is_smb`               TINYINT(1)              NOT NULL,
    `summ`                 DECIMAL(22, 2) UNSIGNED NULL DEFAULT NULL,
    `summ_rub`             DECIMAL(22, 2) UNSIGNED NULL DEFAULT NULL,
    PRIMARY KEY (`long_term_value_guid`, `year`, `is_smb`),
    CONSTRAINT `long_term_value_detail_long_term_value_guid_foreign`
        FOREIGN KEY (`long_term_value_guid`)
            REFERENCES `zakupki`.`long_term_volumes` (`plan_item_guid`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`okei`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`okei`
(
    `code` VARCHAR(20)  NOT NULL,
    `name` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_plan_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_plan_item`
(
    `guid`                      VARCHAR(36)   NOT NULL,
    `notice_info_guid`          VARCHAR(36)   NULL DEFAULT NULL,
    `lot_guid`                  VARCHAR(36)   NULL DEFAULT NULL,
    `okato`                     VARCHAR(11)   NULL DEFAULT NULL,
    `region`                    VARCHAR(1000) NULL DEFAULT NULL,
    `is_general_address`        TINYINT(1)    NULL DEFAULT NULL,
    `purchase_method_code`      INT           NULL DEFAULT NULL,
    `purchase_method_name`      VARCHAR(2000) NULL DEFAULT NULL,
    `is_electronic`             TINYINT(1)    NULL DEFAULT NULL,
    `planned_after_second_year` TINYINT(1)    NULL DEFAULT NULL,
    `is_purchase_ignored`       TINYINT(1)    NULL DEFAULT NULL,
    `purchase_period_year`      INT           NULL DEFAULT NULL,
    PRIMARY KEY (`guid`),
    INDEX `purchase_plan_item_okato_foreign` (`okato` ASC) VISIBLE,
    CONSTRAINT `purchase_plan_item_guid_foreign`
        FOREIGN KEY (`guid`)
            REFERENCES `zakupki`.`plan_item` (`guid`),
    CONSTRAINT `purchase_plan_item_okato_foreign`
        FOREIGN KEY (`okato`)
            REFERENCES `zakupki`.`okato` (`code`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_plan_item_row`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_plan_item_row`
(
    `plan_item_guid`               VARCHAR(36)    NOT NULL,
    `ordinal_number`               INT            NOT NULL,
    `additional_info`              VARCHAR(2000)  NULL DEFAULT NULL,
    `okdp_code`                    VARCHAR(20)    NULL DEFAULT NULL,
    `okdp_name`                    VARCHAR(550)   NULL DEFAULT NULL,
    `okpd2_code`                   VARCHAR(20)    NULL DEFAULT NULL,
    `okpd2_name`                   VARCHAR(550)   NULL DEFAULT NULL,
    `okved_code`                   VARCHAR(20)    NULL DEFAULT NULL,
    `okved_name`                   VARCHAR(550)   NULL DEFAULT NULL,
    `okved2_name`                  VARCHAR(550)   NULL DEFAULT NULL,
    `okved2_code`                  VARCHAR(20)    NULL DEFAULT NULL,
    `okato`                        VARCHAR(11)    NULL DEFAULT NULL,
    `region`                       VARCHAR(1000)  NULL DEFAULT NULL,
    `impossible_to_determine_attr` TINYINT(1)     NULL DEFAULT NULL,
    `okei_code`                    VARCHAR(20)    NULL DEFAULT NULL,
    `okei_name`                    VARCHAR(550)   NULL DEFAULT NULL,
    `qty`                          DECIMAL(25, 5) NULL DEFAULT NULL,
    PRIMARY KEY (`plan_item_guid`, `ordinal_number`),
    INDEX `purchase_plan_item_row_okdp_code_foreign` (`okdp_code` ASC) VISIBLE,
    INDEX `purchase_plan_item_row_okpd2_code_foreign` (`okpd2_code` ASC) VISIBLE,
    INDEX `purchase_plan_item_row_okved_foreign` (`okved_code` ASC) VISIBLE,
    INDEX `purchase_plan_item_row_okved2_foreign` (`okved2_code` ASC) VISIBLE,
    INDEX `purchase_plan_item_row_okei_code_foreign` (`okei_code` ASC) VISIBLE,
    INDEX `purchase_plan_item_row_okato_foreign` (`okato` ASC) VISIBLE,
    CONSTRAINT `purchase_plan_item_row_okato_foreign`
        FOREIGN KEY (`okato`)
            REFERENCES `zakupki`.`okato` (`code`),
    CONSTRAINT `purchase_plan_item_row_okdp_code_foreign`
        FOREIGN KEY (`okdp_code`)
            REFERENCES `zakupki`.`okdp` (`code`),
    CONSTRAINT `purchase_plan_item_row_okei_code_foreign`
        FOREIGN KEY (`okei_code`)
            REFERENCES `zakupki`.`okei` (`code`),
    CONSTRAINT `purchase_plan_item_row_okpd2_code_foreign`
        FOREIGN KEY (`okpd2_code`)
            REFERENCES `zakupki`.`okpd2` (`code`),
    CONSTRAINT `purchase_plan_item_row_okved2_foreign`
        FOREIGN KEY (`okved2_code`)
            REFERENCES `zakupki`.`okved2` (`code`),
    CONSTRAINT `purchase_plan_item_row_okved_foreign`
        FOREIGN KEY (`okved_code`)
            REFERENCES `zakupki`.`okved` (`code`),
    CONSTRAINT `purchase_plan_item_row_plan_item_guid_foreign`
        FOREIGN KEY (`plan_item_guid`)
            REFERENCES `zakupki`.`plan_item` (`guid`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zakupki`.`contract_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`contract_status`
(
    `code` VARCHAR(1)  NOT NULL,
    `name` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`plan_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`plan_position`
(
    `guid`                     VARCHAR(36)   NOT NULL,
    `plan_guid`                VARCHAR(36)   NOT NULL,
    `plan_registration_number` VARCHAR(10)   NULL,
    `position_number`          INT           NOT NULL,
    `lot_plan_position`        VARCHAR(10)   NULL,
    `contract_subject`         VARCHAR(4000) NOT NULL,
    PRIMARY KEY (`guid`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_notice_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_notice_info`
(
    `guid`                  VARCHAR(36)   NOT NULL,
    `number`                VARCHAR(11)   NOT NULL,
    `publication_date_time` DATETIME      NULL,
    `name`                  VARCHAR(2000) NOT NULL,
    PRIMARY KEY (`guid`, `number`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_type`
(
    `code` VARCHAR(5)   NOT NULL,
    `name` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`contract`
(
    `guid`                                             VARCHAR(36)    NOT NULL,
    `registration_number`                              VARCHAR(23)    NULL,
    `notice_44fz`                                      TINYINT(1)     NULL,
    `notice_not_placed_by_fz223p5s4`                   TINYINT(1)     NULL,
    `notice_44_num`                                    VARCHAR(500)   NULL,
    `lot_44_num`                                       VARCHAR(200)   NULL,
    `termination`                                      TINYINT(1)     NOT NULL,
    `extension`                                        TINYINT(1)     NOT NULL,
    `prolongation`                                     TINYINT(1)     NOT NULL,
    `customer_appeale_or_needs_approval`               TINYINT(1)     NULL,
    `customer_approval_or_antimonopoly_descision_date` DATETIME       NULL,
    `start_execution_term`                             VARCHAR(2000)  NULL,
    `end_execution_term`                               VARCHAR(2000)  NULL,
    `plan_position_guid`                               VARCHAR(36)    NULL,
    `url_eis`                                          TEXT(3000)     NULL,
    `url_vsrz`                                         TEXT(3000)     NULL,
    `url_kis_rmis`                                     TEXT(3000)     NULL,
    `create_date_time`                                 DATETIME       NOT NULL,
    `customer_inn`                                     VARCHAR(12)    NOT NULL,
    `placer_inn`                                       VARCHAR(12)    NOT NULL,
    `detached_org_inn`                                 VARCHAR(12)    NULL,
    `publication_date`                                 DATETIME       NULL,
    `contract_status_code`                             VARCHAR(1)     NULL,
    `version`                                          INT            NULL,
    `modification_description`                         VARCHAR(2000)  NULL,
    `digital_purchase`                                 TINYINT(1)     NOT NULL,
    `digital_purchase_code`                            VARCHAR(6)     NOT NULL,
    `provider`                                         TINYINT(1)     NOT NULL,
    `provider_code`                                    VARCHAR(2)     NULL,
    `change_contract`                                  TINYINT(1)     NOT NULL,
    `contract_reg_number`                              VARCHAR(23)    NULL,
    `name`                                             VARCHAR(500)   NULL,
    `contract_date`                                    DATE           NOT NULL,
    `approve_date`                                     DATE           NULL,
    `purchase_notice_info_guid`                        VARCHAR(36)    NULL,
    `purchase_notice_info_number`                      VARCHAR(11)    NULL,
    `lotGuid`                                          VARCHAR(36)    NULL,
    `subject_contract`                                 VARCHAR(2000)  NOT NULL,
    `purchase_type_code`                               VARCHAR(5)     NOT NULL,
    `resume_date`                                      DATE           NULL,
    `has_subcontractor`                                TINYINT(1)     NULL,
    `has_subcontractor_code`                           VARCHAR(2)     NULL,
    `subcontractors_total`                             VARCHAR(200)   NULL,
    `has_good_info`                                    TINYINT(1)     NULL,
    `additional_info`                                  VARCHAR(2000)  NULL,
    `price`                                            DECIMAL(22, 2) NOT NULL,
    `exchange_rate`                                    DECIMAL(16, 6) NULL,
    `exchange_rate_date`                               DATE           NULL,
    `rub_price`                                        DECIMAL(22, 2) NULL,
    `currency_code`                                    VARCHAR(3)     NOT NULL,
    `start_execution_date`                             DATE           NULL,
    `end_execution_date`                               DATE           NULL,
    `has_okpd_and_okdp_rows`                           TINYINT(1)     NULL,
    `has_okpd2_rows`                                   TINYINT(1)     NULL,
    `is_electronic_place`                              TINYINT(1)     NULL,
    `electronic_place_name`                            VARCHAR(1000)  NULL,
    `electronic_place_url`                             VARCHAR(1000)  NULL,
    `electronic_place_publish_date`                    DATETIME       NULL,
    `electronic_place_guid`                            VARCHAR(36)    NULL,
    PRIMARY KEY (`guid`),
    INDEX `fk_contract_customer1_idx` (`customer_inn` ASC) VISIBLE,
    INDEX `fk_contract_customer2_idx` (`placer_inn` ASC) VISIBLE,
    INDEX `fk_contract_customer3_idx` (`detached_org_inn` ASC) VISIBLE,
    INDEX `fk_contract_contract_status1_idx` (`contract_status_code` ASC) VISIBLE,
    INDEX `fk_contract_plan_position1_idx` (`plan_position_guid` ASC) VISIBLE,
    INDEX `fk_contract_purchase_notice_info1_idx` (`purchase_notice_info_guid` ASC, `purchase_notice_info_number` ASC) VISIBLE,
    INDEX `fk_contract_purchase_type1_idx` (`purchase_type_code` ASC) VISIBLE,
    INDEX `fk_contract_currency1_idx` (`currency_code` ASC) VISIBLE,
    CONSTRAINT `fk_contract_customer1`
        FOREIGN KEY (`customer_inn`)
            REFERENCES `zakupki`.`customer` (`inn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_customer2`
        FOREIGN KEY (`placer_inn`)
            REFERENCES `zakupki`.`customer` (`inn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_customer3`
        FOREIGN KEY (`detached_org_inn`)
            REFERENCES `zakupki`.`customer` (`inn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_contract_status1`
        FOREIGN KEY (`contract_status_code`)
            REFERENCES `zakupki`.`contract_status` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_plan_position1`
        FOREIGN KEY (`plan_position_guid`)
            REFERENCES `zakupki`.`plan_position` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_purchase_notice_info1`
        FOREIGN KEY (`purchase_notice_info_guid`, `purchase_notice_info_number`)
            REFERENCES `zakupki`.`purchase_notice_info` (`guid`, `number`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_purchase_type1`
        FOREIGN KEY (`purchase_type_code`)
            REFERENCES `zakupki`.`purchase_type` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_currency1`
        FOREIGN KEY (`currency_code`)
            REFERENCES `zakupki`.`currency` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`country`
(
    `code`       VARCHAR(3)   NOT NULL,
    `short_name` VARCHAR(100) NOT NULL,
    `full_name`  VARCHAR(500) NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`oktmo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`oktmo`
(
    `code` VARCHAR(11)   NOT NULL,
    `name` VARCHAR(1050) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`supplier_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`supplier_address`
(
    `id`                  BIGINT        NOT NULL AUTO_INCREMENT,
    `egrul_egrip_changed` TINYINT(1)    NOT NULL,
    `country_code`        VARCHAR(3)    NULL,
    `post_code`           VARCHAR(7)    NOT NULL,
    `oktmo_code`          VARCHAR(11)   NULL,
    `oktmo_name`          VARCHAR(1050) NULL,
    `region_code`         INT           NULL,
    `region_name`         VARCHAR(255)  NULL,
    `area`                VARCHAR(255)  NULL,
    `city`                VARCHAR(255)  NULL,
    `settlement`          VARCHAR(255)  NULL,
    `street`              VARCHAR(255)  NULL,
    `email`               VARCHAR(200)  NULL,
    `phone`               VARCHAR(200)  NULL,
    `office`              VARCHAR(255)  NULL,
    `building`            VARCHAR(50)   NULL,
    `house`               VARCHAR(255)  NULL,
    `planning_structure`  VARCHAR(255)  NULL,
    `admin_division`      VARCHAR(255)  NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_supplier_address_country1_idx` (`country_code` ASC) VISIBLE,
    INDEX `fk_supplier_address_oktmo1_idx` (`oktmo_code` ASC) VISIBLE,
    CONSTRAINT `fk_supplier_address_country1`
        FOREIGN KEY (`country_code`)
            REFERENCES `zakupki`.`country` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_supplier_address_oktmo1`
        FOREIGN KEY (`oktmo_code`)
            REFERENCES `zakupki`.`oktmo` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`supplier`
(
    `inn`                       VARCHAR(12)   NOT NULL,
    `name`                      VARCHAR(1000) NOT NULL,
    `short_name`                VARCHAR(1000) NULL,
    `brand_name`                VARCHAR(1000) NULL,
    `additional_full_name`      VARCHAR(1000) NULL,
    `kpp`                       VARCHAR(9)    NULL,
    `okpo`                      VARCHAR(10)   NULL,
    `code`                      VARCHAR(200)  NULL,
    `additional_code`           VARCHAR(200)  NULL,
    `additional_info`           VARCHAR(2000) NULL,
    `type`                      VARCHAR(1)    NOT NULL,
    `provider`                  TINYINT(1)    NOT NULL,
    `provider_code`             VARCHAR(2)    NULL,
    `subcontractor`             TINYINT(1)    NOT NULL,
    `subcontractor_code`        VARCHAR(2)    NULL,
    `individual`                TINYINT(1)    NULL,
    `non_resident`              TINYINT(1)    NOT NULL,
    `registration_date`         DATE          NULL,
    `tax`                       TINYINT(1)    NULL,
    `okopf_code`                VARCHAR(5)    NULL,
    `okopf_name`                VARCHAR(250)  NULL,
    `address_id`                BIGINT        NULL,
    `address_rf_id`             BIGINT        NULL,
    `provider_include_msp_date` DATE          NULL,
    `is_in_order_173n`          TINYINT(1)    NULL,
    PRIMARY KEY (`inn`),
    INDEX `fk_supplier_okopf1_idx` (`okopf_code` ASC) VISIBLE,
    INDEX `fk_supplier_supplier_address1_idx` (`address_id` ASC) VISIBLE,
    INDEX `fk_supplier_supplier_address2_idx` (`address_rf_id` ASC) VISIBLE,
    CONSTRAINT `fk_supplier_okopf1`
        FOREIGN KEY (`okopf_code`)
            REFERENCES `zakupki`.`okopf` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_supplier_supplier_address1`
        FOREIGN KEY (`address_id`)
            REFERENCES `zakupki`.`supplier_address` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_supplier_supplier_address2`
        FOREIGN KEY (`address_rf_id`)
            REFERENCES `zakupki`.`supplier_address` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`supplier_to_contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`supplier_to_contract`
(
    `contract_guid` VARCHAR(36) NOT NULL,
    `supplier_inn`  VARCHAR(12) NOT NULL,
    INDEX `fk_supplier_to_contract_contract1_idx` (`contract_guid` ASC) VISIBLE,
    PRIMARY KEY (`contract_guid`, `supplier_inn`),
    INDEX `fk_supplier_to_contract_supplier1_idx` (`supplier_inn` ASC) VISIBLE,
    CONSTRAINT `fk_supplier_to_contract_contract1`
        FOREIGN KEY (`contract_guid`)
            REFERENCES `zakupki`.`contract` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_supplier_to_contract_supplier1`
        FOREIGN KEY (`supplier_inn`)
            REFERENCES `zakupki`.`supplier` (`inn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`okpd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`okpd`
(
    `code` VARCHAR(20)  NOT NULL,
    `name` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`contract_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`contract_position`
(
    `contract_guid`                VARCHAR(36)    NOT NULL,
    `ordinal_number`               INT            NOT NULL,
    `guid`                         VARCHAR(36)    NULL,
    `name`                         VARCHAR(2000)  NULL,
    `okdp_code`                    VARCHAR(20)    NULL,
    `okdp_name`                    VARCHAR(500)   NULL,
    `okpd_code`                    VARCHAR(20)    NULL,
    `okpd_name`                    VARCHAR(550)   NULL,
    `okpd2_code`                   VARCHAR(20)    NULL,
    `okpd2_name`                   VARCHAR(550)   NULL,
    `country_code`                 VARCHAR(3)     NULL,
    `producer_country`             TINYINT(1)     NULL,
    `impossible_to_determine_attr` TINYINT(1)     NULL,
    `okei_code`                    VARCHAR(20)    NULL,
    `okei_name`                    VARCHAR(550)   NULL,
    `qty`                          DECIMAL(30, 5) NULL,
    INDEX `fk_contract_position_contract1_idx` (`contract_guid` ASC) VISIBLE,
    PRIMARY KEY (`contract_guid`, `ordinal_number`),
    INDEX `fk_contract_position_okdp1_idx` (`okdp_code` ASC) VISIBLE,
    INDEX `fk_contract_position_okpd1_idx` (`okpd_code` ASC) VISIBLE,
    INDEX `fk_contract_position_okpd21_idx` (`okpd2_code` ASC) VISIBLE,
    INDEX `fk_contract_position_country1_idx` (`country_code` ASC) VISIBLE,
    INDEX `fk_contract_position_okei1_idx` (`okei_code` ASC) VISIBLE,
    UNIQUE INDEX `guid_UNIQUE` (`guid` ASC) VISIBLE,
    CONSTRAINT `fk_contract_position_contract1`
        FOREIGN KEY (`contract_guid`)
            REFERENCES `zakupki`.`contract` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_position_okdp1`
        FOREIGN KEY (`okdp_code`)
            REFERENCES `zakupki`.`okdp` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_position_okpd1`
        FOREIGN KEY (`okpd_code`)
            REFERENCES `zakupki`.`okpd` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_position_okpd21`
        FOREIGN KEY (`okpd2_code`)
            REFERENCES `zakupki`.`okpd2` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_position_country1`
        FOREIGN KEY (`country_code`)
            REFERENCES `zakupki`.`country` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contract_position_okei1`
        FOREIGN KEY (`okei_code`)
            REFERENCES `zakupki`.`okei` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`supplier_without_inn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`supplier_without_inn`
(
    `id`                        BIGINT        NOT NULL AUTO_INCREMENT,
    `name`                      VARCHAR(1000) NOT NULL,
    `contract_guid`             VARCHAR(36)   NOT NULL,
    `short_name`                VARCHAR(1000) NULL,
    `brand_name`                VARCHAR(1000) NULL,
    `additional_full_name`      VARCHAR(1000) NULL,
    `inn`                       VARCHAR(12)   NULL,
    `kpp`                       VARCHAR(9)    NULL,
    `okpo`                      VARCHAR(10)   NULL,
    `code`                      VARCHAR(200)  NULL,
    `additional_code`           VARCHAR(200)  NULL,
    `additional_info`           VARCHAR(2000) NULL,
    `type`                      VARCHAR(1)    NOT NULL,
    `provider`                  TINYINT(1)    NOT NULL,
    `provider_code`             VARCHAR(2)    NULL,
    `subcontractor`             TINYINT(1)    NOT NULL,
    `subcontractor_code`        VARCHAR(2)    NULL,
    `individual`                TINYINT(1)    NULL,
    `non_resident`              TINYINT(1)    NOT NULL,
    `registration_date`         DATE          NULL,
    `tax`                       TINYINT(1)    NULL,
    `okopf_code`                VARCHAR(5)    NULL,
    `okopf_name`                VARCHAR(250)  NULL,
    `address_id`                BIGINT        NOT NULL,
    `address_rf_id`             BIGINT        NULL,
    `provider_include_msp_date` DATE          NULL,
    `is_in_order_173n`          TINYINT(1)    NULL,
    INDEX `fk_supplier_okopf1_idx` (`okopf_code` ASC) VISIBLE,
    INDEX `fk_supplier_supplier_address1_idx` (`address_id` ASC) VISIBLE,
    INDEX `fk_supplier_supplier_address2_idx` (`address_rf_id` ASC) VISIBLE,
    PRIMARY KEY (`id`),
    INDEX `fk_supplier_without_inn_contract1_idx` (`contract_guid` ASC) VISIBLE,
    CONSTRAINT `fk_supplier_okopf10`
        FOREIGN KEY (`okopf_code`)
            REFERENCES `zakupki`.`okopf` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_supplier_supplier_address10`
        FOREIGN KEY (`address_id`)
            REFERENCES `zakupki`.`supplier_address` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_supplier_supplier_address20`
        FOREIGN KEY (`address_rf_id`)
            REFERENCES `zakupki`.`supplier_address` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_supplier_without_inn_contract1`
        FOREIGN KEY (`contract_guid`)
            REFERENCES `zakupki`.`contract` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_notice_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_notice_status`
(
    `code` VARCHAR(1)  NOT NULL,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`electornic_place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`electornic_place`
(
    `electronic_place_id` INT           NOT NULL,
    `name`                VARCHAR(1000) NOT NULL,
    `url`                 VARCHAR(1000) NULL,
    PRIMARY KEY (`electronic_place_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_notice_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_notice_data`
(
    `guid`                            VARCHAR(36)   NOT NULL,
    `create_date_time`                DATETIME      NOT NULL,
    `url_eis`                         TEXT(3000)    NULL,
    `url_vsrz`                        TEXT(3000)    NULL,
    `url_kis_rmis`                    TEXT(3000)    NULL,
    `registration_number`             VARCHAR(11)   NULL,
    `name`                            VARCHAR(2000) NOT NULL,
    `customer_inn`                    VARCHAR(12)   NOT NULL,
    `detached_org_inn`                VARCHAR(12)   NULL,
    `blocked_customer_inn`            VARCHAR(12)   NULL,
    `purchase_method_code`            INT           NULL,
    `purchase_code_name`              VARCHAR(2000) NULL,
    `placer_inn`                      VARCHAR(12)   NOT NULL,
    `publication_date_time`           DATETIME      NULL,
    `purchase_notice_status_code`     VARCHAR(1)    NULL,
    `version`                         INT           NULL,
    `modification_description`        VARCHAR(2000) NULL,
    `not_dishonest`                   TINYINT(1)    NULL,
    `modification_date`               DATETIME      NULL,
    `save_user_id`                    INT           NULL,
    `delivery_place_indication`       VARCHAR(20)   NULL,
    `emergency`                       TINYINT(1)    NULL,
    `joint_purchase`                  TINYINT(1)    NULL,
    `for_small_or_middle`             TINYINT(1)    NULL,
    `change_decision_date`            DATE          NULL,
    `antimonopoly_decision_taken`     TINYINT(1)    NULL,
    `additional_info`                 TEXT(10000)   NULL,
    `appl_submision_place`            TEXT(3000)    NULL,
    `appl_submision_start_date`       DATE          NULL,
    `appl_submision_order`            TEXT(3000)    NULL,
    `envelope_opening_order`          TEXT(3000)    NULL,
    `appl_examination_order`          TEXT(3000)    NULL,
    `summingup_order`                 TEXT(3000)    NULL,
    `auction_order`                   TEXT(3000)    NULL,
    `consideration_second_part_place` TEXT(3000)    NULL,
    `consideration_second_part_order` TEXT(3000)    NULL,
    `is_upload_complete`              TINYINT(1)    NULL,
    `electronic_place_id`             INT           NULL,
    `submission_close_date_time`      DATETIME      NULL,
    `publication_planned_date`        DATE          NULL,
    PRIMARY KEY (`guid`),
    INDEX `fk_purchase_notice_data_customer1_idx` (`customer_inn` ASC) VISIBLE,
    INDEX `fk_purchase_notice_data_customer2_idx` (`detached_org_inn` ASC) VISIBLE,
    INDEX `fk_purchase_notice_data_customer3_idx` (`blocked_customer_inn` ASC) VISIBLE,
    INDEX `fk_purchase_notice_data_customer4_idx` (`placer_inn` ASC) VISIBLE,
    INDEX `fk_purchase_notice_data_purchase_notice_status1_idx` (`purchase_notice_status_code` ASC) VISIBLE,
    INDEX `fk_purchase_notice_data_purchase_notice_electornic_place1_idx` (`electronic_place_id` ASC) VISIBLE,
    CONSTRAINT `fk_purchase_notice_data_customer1`
        FOREIGN KEY (`customer_inn`)
            REFERENCES `zakupki`.`customer` (`inn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_data_customer2`
        FOREIGN KEY (`detached_org_inn`)
            REFERENCES `zakupki`.`customer` (`inn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_data_customer3`
        FOREIGN KEY (`blocked_customer_inn`)
            REFERENCES `zakupki`.`customer` (`inn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_data_customer4`
        FOREIGN KEY (`placer_inn`)
            REFERENCES `zakupki`.`customer` (`inn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_data_purchase_notice_status1`
        FOREIGN KEY (`purchase_notice_status_code`)
            REFERENCES `zakupki`.`purchase_notice_status` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_data_purchase_notice_electornic_place1`
        FOREIGN KEY (`electronic_place_id`)
            REFERENCES `zakupki`.`electornic_place` (`electronic_place_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_notice_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_notice_contact`
(
    `purchase_notice_data_guid` VARCHAR(36)   NOT NULL,
    `first_name`                VARCHAR(300)  NULL,
    `middle_name`               VARCHAR(300)  NULL,
    `last_name`                 VARCHAR(300)  NULL,
    `phone`                     VARCHAR(300)  NULL,
    `fax`                       VARCHAR(300)  NULL,
    `email`                     VARCHAR(300)  NULL,
    `additional_contact_info`   VARCHAR(2000) NULL,
    INDEX `fk_purchase_notice_contact_purchase_notice_data1_idx` (`purchase_notice_data_guid` ASC) VISIBLE,
    PRIMARY KEY (`purchase_notice_data_guid`),
    CONSTRAINT `fk_purchase_notice_contact_purchase_notice_data1`
        FOREIGN KEY (`purchase_notice_data_guid`)
            REFERENCES `zakupki`.`purchase_notice_data` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_notice_documentation_delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_notice_documentation_delivery`
(
    `purchase_notice_data_guid` VARCHAR(36)    NOT NULL,
    `delivery_start_date_time`  DATETIME       NOT NULL,
    `delivery_end_date_time`    DATETIME       NOT NULL,
    `place`                     VARCHAR(2000)  NOT NULL,
    `documentation_procedure`   VARCHAR(2000)  NOT NULL,
    `currency_code`             VARCHAR(3)     NULL,
    `sum`                       DECIMAL(22, 2) NULL,
    `payment_procedure`         VARCHAR(2000)  NULL,
    INDEX `fk_purchase_notice_documentation_delivary_purchase_notice_d_idx` (`purchase_notice_data_guid` ASC) VISIBLE,
    PRIMARY KEY (`purchase_notice_data_guid`),
    INDEX `fk_purchase_notice_documentation_delivery_currency1_idx` (`currency_code` ASC) VISIBLE,
    CONSTRAINT `fk_purchase_notice_documentation_delivary_purchase_notice_data1`
        FOREIGN KEY (`purchase_notice_data_guid`)
            REFERENCES `zakupki`.`purchase_notice_data` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_documentation_delivery_currency1`
        FOREIGN KEY (`currency_code`)
            REFERENCES `zakupki`.`currency` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`placing_procedure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`placing_procedure`
(
    `purchase_notice_data_guid` VARCHAR(36)   NOT NULL,
    `examination_place`         VARCHAR(2000) NULL,
    `examination_date_time`     DATETIME      NULL,
    `summingup_date_time`       DATETIME      NOT NULL,
    `summingup_place`           VARCHAR(2000) NULL,
    INDEX `fk_placing_procedure_purchase_notice_data1_idx` (`purchase_notice_data_guid` ASC) VISIBLE,
    CONSTRAINT `fk_placing_procedure_purchase_notice_data1`
        FOREIGN KEY (`purchase_notice_data_guid`)
            REFERENCES `zakupki`.`purchase_notice_data` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_notice_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_notice_extra`
(
    `purchase_notice_data_guid` VARCHAR(36)    NOT NULL,
    `integr_code`               VARCHAR(50)    NOT NULL,
    `description`               VARCHAR(200)   NULL,
    `text`                      TEXT(2000)     NULL,
    `number_int`                INT            NULL,
    `number`                    DECIMAL(22, 2) NULL,
    `boolean`                   TINYINT(1)     NULL,
    `datetime`                  DATETIME       NULL,
    `date`                      DATE           NULL,
    `url`                       TEXT(1000)     NULL,
    `nsi_code`                  VARCHAR(20)    NULL,
    `nsi_name`                  VARCHAR(550)   NULL,
    INDEX `fk_purchase_notice_extras_purchase_notice_data1_idx` (`purchase_notice_data_guid` ASC) VISIBLE,
    PRIMARY KEY (`integr_code`, `purchase_notice_data_guid`),
    CONSTRAINT `fk_purchase_notice_extras_purchase_notice_data1`
        FOREIGN KEY (`purchase_notice_data_guid`)
            REFERENCES `zakupki`.`purchase_notice_data` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`delivary_place_indication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`delivary_place_indication`
(
    `code` VARCHAR(3)  NOT NULL,
    `name` VARCHAR(60) NOT NULL,
    PRIMARY KEY (`code`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_notice_lot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_notice_lot`
(
    `guid`                           VARCHAR(36) NOT NULL,
    `purchase_notice_guid`           VARCHAR(36) NOT NULL,
    `ordinal_number`                 INT         NOT NULL,
    `lot_edit_enabled`               TINYINT(1)  NOT NULL,
    `delivary_place_indication_code` VARCHAR(3)  NULL,
    `joint_lot`                      TINYINT(1)  NULL,
    `plan_guid`                      VARCHAR(36) NULL,
    `position_number`                INT         NULL,
    `lot_plan_position`              VARCHAR(36) NULL,
    `position_guid`                  VARCHAR(36) NULL,
    `contract_subject`               TEXT        NULL,
    `cancelled`                      TINYINT(1)  NOT NULL,
    `cancel_date`                    DATE        NULL,
    `cancel_info`                    TEXT(2000)  NULL,
    `emergency`                      TINYINT(1)  NULL,
    INDEX `fk_purchase_notice_lot_purchase_notice_data1_idx` (`purchase_notice_guid` ASC) VISIBLE,
    PRIMARY KEY (`guid`),
    INDEX `fk_purchase_notice_lot_delivary_place_indication1_idx` (`delivary_place_indication_code` ASC) VISIBLE,
    CONSTRAINT `fk_purchase_notice_lot_purchase_notice_data1`
        FOREIGN KEY (`purchase_notice_guid`)
            REFERENCES `zakupki`.`purchase_notice_data` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_lot_delivary_place_indication1`
        FOREIGN KEY (`delivary_place_indication_code`)
            REFERENCES `zakupki`.`delivary_place_indication` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_notice_lot_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_notice_lot_data`
(
    `purchase_notice_lot_guid`         VARCHAR(36)    NOT NULL,
    `subject`                          TEXT(2000)     NOT NULL,
    `currency_code`                    VARCHAR(3)     NULL,
    `exchange_rate`                    DECIMAL(16, 6) NULL,
    `exchange_rate_date`               DATE           NULL,
    `initial_sum`                      DECIMAL(22, 2) NULL,
    `starting_contract_price_rub`      DECIMAL(22, 2) NULL,
    `price_formula`                    TEXT(2000)     NULL,
    `commodity_price`                  DECIMAL(22, 2) NULL,
    `commodity_price_rub`              DECIMAL(22, 2) NULL,
    `max_contract_price`               DECIMAL(22, 2) NULL,
    `max_contract_price_rub`           DECIMAL(22, 2) NULL,
    `initial_sum_info`                 TEXT(2000)     NULL,
    `order_pricing`                    TEXT(2000)     NULL,
    `delivery_state`                   TEXT(2000)     NULL,
    `delivery_region`                  TEXT(2000)     NULL,
    `delivery_region_okato`            VARCHAR(11)    NULL,
    `delivery_address`                 TEXT(2000)     NULL,
    `for_small_or_middle`              TINYINT(1)     NULL,
    `exclude_purchase_from_plan`       TINYINT(1)     NULL,
    `subcontractors_requirement`       TINYINT(1)     NULL,
    `ignored_purchase`                 TINYINT(1)     NULL,
    `purchase_category_code`           INT            NULL,
    `centralized`                      TINYINT(1)     NULL,
    `purchase_description`             TEXT(2000)     NULL,
    `application_supply_needed`        TINYINT(1)     NULL,
    `application_supply_summ`          DECIMAL(22, 2) NULL,
    `application_supply_currency_code` VARCHAR(3)     NULL,
    `application_supply_extra`         TEXT(2000)     NULL,
    `major_contract_conditions`        TEXT(2000)     NULL,
    `antimonopoly_decision_taken`      TINYINT(1)     NULL,
    INDEX `fk_purchase_notice_lot_data_purchase_notice_lot1_idx` (`purchase_notice_lot_guid` ASC) VISIBLE,
    PRIMARY KEY (`purchase_notice_lot_guid`),
    INDEX `fk_purchase_notice_lot_data_currency1_idx` (`currency_code` ASC) VISIBLE,
    INDEX `fk_purchase_notice_lot_data_okato1_idx` (`delivery_region_okato` ASC) VISIBLE,
    INDEX `fk_purchase_notice_lot_data_purchase_category1_idx` (`purchase_category_code` ASC) VISIBLE,
    INDEX `fk_purchase_notice_lot_data_currency2_idx` (`application_supply_currency_code` ASC) VISIBLE,
    CONSTRAINT `fk_purchase_notice_lot_data_purchase_notice_lot1`
        FOREIGN KEY (`purchase_notice_lot_guid`)
            REFERENCES `zakupki`.`purchase_notice_lot` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_lot_data_currency1`
        FOREIGN KEY (`currency_code`)
            REFERENCES `zakupki`.`currency` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_lot_data_okato1`
        FOREIGN KEY (`delivery_region_okato`)
            REFERENCES `zakupki`.`okato` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_lot_data_purchase_category1`
        FOREIGN KEY (`purchase_category_code`)
            REFERENCES `zakupki`.`purchase_category` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_lot_data_currency2`
        FOREIGN KEY (`application_supply_currency_code`)
            REFERENCES `zakupki`.`currency` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`purchase_notice_lot_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`purchase_notice_lot_item`
(
    `guid`                          VARCHAR(36)    NOT NULL,
    `purchase_notice_lot_data_guid` VARCHAR(36)    NOT NULL,
    `ordinalNumber`                 INT            NOT NULL,
    `okdp_code`                     VARCHAR(20)    NULL,
    `okdp_name`                     VARCHAR(500)   NULL,
    `okpd2_code`                    VARCHAR(20)    NULL,
    `okpd2_name`                    VARCHAR(550)   NULL,
    `okved_code`                    VARCHAR(20)    NULL,
    `okved_name`                    VARCHAR(550)   NULL,
    `okved2_code`                   VARCHAR(20)    NULL,
    `okved2_name`                   VARCHAR(550)   NULL,
    `okei_code`                     VARCHAR(20)    NULL,
    `okei_name`                     VARCHAR(550)   NULL,
    `qty`                           DECIMAL(30, 5) NULL,
    `additional_info`               TEXT(1000)     NULL,
    `delivery_state`                TEXT(2000)     NULL,
    `delivery_region`               TEXT(2000)     NULL,
    `delivery_region_okato`         VARCHAR(11)    NULL,
    `delivery_address`              TEXT(2000)     NULL,
    `commodity_item_price`          DECIMAL(22, 2) NULL,
    `commodity_item_price_rub`      DECIMAL(22, 2) NULL,
    INDEX `fk_purchase_notice_lot_item_purchase_notice_lot_data1_idx` (`purchase_notice_lot_data_guid` ASC) VISIBLE,
    PRIMARY KEY (`guid`),
    INDEX `fk_purchase_notice_lot_item_okato1_idx` (`delivery_region_okato` ASC) VISIBLE,
    INDEX `fk_purchase_notice_lot_item_okdp1_idx` (`okdp_code` ASC) VISIBLE,
    INDEX `fk_purchase_notice_lot_item_okpd21_idx` (`okpd2_code` ASC) VISIBLE,
    INDEX `fk_purchase_notice_lot_item_okved1_idx` (`okved_code` ASC) VISIBLE,
    INDEX `fk_purchase_notice_lot_item_okved21_idx` (`okved2_code` ASC) VISIBLE,
    INDEX `fk_purchase_notice_lot_item_okei1_idx` (`okei_code` ASC) VISIBLE,
    CONSTRAINT `fk_purchase_notice_lot_item_purchase_notice_lot_data1`
        FOREIGN KEY (`purchase_notice_lot_data_guid`)
            REFERENCES `zakupki`.`purchase_notice_lot_data` (`purchase_notice_lot_guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_lot_item_okato1`
        FOREIGN KEY (`delivery_region_okato`)
            REFERENCES `zakupki`.`okato` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_lot_item_okdp1`
        FOREIGN KEY (`okdp_code`)
            REFERENCES `zakupki`.`okdp` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_lot_item_okpd21`
        FOREIGN KEY (`okpd2_code`)
            REFERENCES `zakupki`.`okpd2` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_lot_item_okved1`
        FOREIGN KEY (`okved_code`)
            REFERENCES `zakupki`.`okved` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_lot_item_okved21`
        FOREIGN KEY (`okved2_code`)
            REFERENCES `zakupki`.`okved2` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_purchase_notice_lot_item_okei1`
        FOREIGN KEY (`okei_code`)
            REFERENCES `zakupki`.`okei` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`joint_lot_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`joint_lot_data`
(
    `purchase_notice_lot_guid`       VARCHAR(36)   NOT NULL,
    `customer_inn`                   VARCHAR(12)   NOT NULL,
    `additional_info`                TEXT(2000)    NULL,
    `delivary_place_indication_code` VARCHAR(3)    NULL,
    `lot_customer_edit_enabled`      TINYINT(1)    NOT NULL,
    `tax`                            TINYINT(1)    NULL,
    `non_resident`                   TINYINT(1)    NULL,
    `non_resident_name`              VARCHAR(1000) NULL,
    `non_resident_code`              VARCHAR(200)  NULL,
    `country_code`                   VARCHAR(3)    NULL,
    INDEX `fk_joint_lot_data_purchase_notice_lot1_idx` (`purchase_notice_lot_guid` ASC) VISIBLE,
    INDEX `fk_joint_lot_data_customer1_idx` (`customer_inn` ASC) VISIBLE,
    PRIMARY KEY (`purchase_notice_lot_guid`, `customer_inn`),
    INDEX `fk_joint_lot_data_delivary_place_indication1_idx` (`delivary_place_indication_code` ASC) VISIBLE,
    INDEX `fk_joint_lot_data_country1_idx` (`country_code` ASC) VISIBLE,
    CONSTRAINT `fk_joint_lot_data_purchase_notice_lot1`
        FOREIGN KEY (`purchase_notice_lot_guid`)
            REFERENCES `zakupki`.`purchase_notice_lot` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_joint_lot_data_customer1`
        FOREIGN KEY (`customer_inn`)
            REFERENCES `zakupki`.`customer` (`inn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_joint_lot_data_delivary_place_indication1`
        FOREIGN KEY (`delivary_place_indication_code`)
            REFERENCES `zakupki`.`delivary_place_indication` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_joint_lot_data_country1`
        FOREIGN KEY (`country_code`)
            REFERENCES `zakupki`.`country` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`lot_customer_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`lot_customer_data`
(
    `joint_lot_data_purchase_notice_lot_guid` VARCHAR(36)    NOT NULL,
    `joint_lot_data_customer_inn`             VARCHAR(12)    NOT NULL,
    `currency_code`                           VARCHAR(3)     NULL,
    `exchange_rate`                           DECIMAL(16, 6) NULL,
    `exchange_rate_date`                      DATE           NULL,
    `initial_sum`                             DECIMAL(22, 2) NULL,
    `starting_contract_price_rub`             DECIMAL(22, 2) NULL,
    `price_formula`                           TEXT(2000)     NOT NULL,
    `price`                                   DECIMAL(22, 2) NOT NULL,
    `price_rub`                               DECIMAL(22, 2) NULL,
    `max_contract_price`                      DECIMAL(22, 2) NULL,
    `max_contract_price_rub`                  DECIMAL(22, 2) NULL,
    `exclude_purchase_from_plan`              TINYINT(1)     NULL,
    `order_pricing`                           TEXT(2000)     NULL,
    `delivery_state`                          TEXT(2000)     NULL,
    `delivery_region`                         TEXT(2000)     NULL,
    `delivery_region_okato`                   VARCHAR(11)    NULL,
    `delivery_address`                        TEXT(2000)     NULL,
    `not_in_law_223`                          TINYINT(1)     NULL,
    `plan_guid`                               VARCHAR(36)    NULL,
    `position_number`                         INT            NULL,
    `lot_plan_position`                       VARCHAR(36)    NULL,
    `position_guid`                           VARCHAR(36)    NULL,
    `plan_registration_number`                VARCHAR(10)    NULL,
    INDEX `fk_lot_customer_data_joint_lot_data1_idx` (`joint_lot_data_purchase_notice_lot_guid` ASC,
                                                      `joint_lot_data_customer_inn` ASC) VISIBLE,
    INDEX `fk_lot_customer_data_currency1_idx` (`currency_code` ASC) VISIBLE,
    PRIMARY KEY (`joint_lot_data_purchase_notice_lot_guid`, `joint_lot_data_customer_inn`),
    INDEX `fk_lot_customer_data_okato1_idx` (`delivery_region_okato` ASC) VISIBLE,
    CONSTRAINT `fk_lot_customer_data_joint_lot_data1`
        FOREIGN KEY (`joint_lot_data_purchase_notice_lot_guid`, `joint_lot_data_customer_inn`)
            REFERENCES `zakupki`.`joint_lot_data` (`purchase_notice_lot_guid`, `customer_inn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_lot_customer_data_currency1`
        FOREIGN KEY (`currency_code`)
            REFERENCES `zakupki`.`currency` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_lot_customer_data_okato1`
        FOREIGN KEY (`delivery_region_okato`)
            REFERENCES `zakupki`.`okato` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`joint_customer_lot_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`joint_customer_lot_item`
(
    `guid`                                                      VARCHAR(36)    NOT NULL,
    `lot_customer_data_joint_lot_data_purchase_notice_lot_guid` VARCHAR(36)    NOT NULL,
    `lot_customer_data_joint_lot_data_customer_inn`             VARCHAR(12)    NOT NULL,
    `ordinalNumber`                                             INT            NOT NULL,
    `okdp_code`                                                 VARCHAR(20)    NULL,
    `okdp_name`                                                 VARCHAR(500)   NULL,
    `okpd2_code`                                                VARCHAR(20)    NULL,
    `okpd2_name`                                                VARCHAR(550)   NULL,
    `okved_code`                                                VARCHAR(20)    NULL,
    `okved_name`                                                VARCHAR(550)   NULL,
    `okved2_code`                                               VARCHAR(20)    NULL,
    `okved2_name`                                               VARCHAR(550)   NULL,
    `okei_code`                                                 VARCHAR(20)    NULL,
    `okei_name`                                                 VARCHAR(550)   NULL,
    `qty`                                                       DECIMAL(30, 5) NULL,
    `additional_info`                                           TEXT(1000)     NULL,
    `delivery_state`                                            TEXT(2000)     NULL,
    `delivery_region`                                           TEXT(2000)     NULL,
    `delivary_region_okato`                                     VARCHAR(11)    NULL,
    `delivery_address`                                          TEXT(2000)     NULL,
    `commodity_item_price`                                      DECIMAL(22, 2) NULL,
    `commodity_item_price_rub`                                  DECIMAL(22, 2) NULL,
    INDEX `fk_joint_customer_lot_item_lot_customer_data1_idx` (`lot_customer_data_joint_lot_data_purchase_notice_lot_guid`
                                                               ASC, `lot_customer_data_joint_lot_data_customer_inn`
                                                               ASC) VISIBLE,
    PRIMARY KEY (`guid`),
    INDEX `fk_joint_customer_lot_item_okdp1_idx` (`okdp_code` ASC) VISIBLE,
    INDEX `fk_joint_customer_lot_item_okpd21_idx` (`okpd2_code` ASC) VISIBLE,
    INDEX `fk_joint_customer_lot_item_okved1_idx` (`okved_code` ASC) VISIBLE,
    INDEX `fk_joint_customer_lot_item_okved21_idx` (`okved2_code` ASC) VISIBLE,
    INDEX `fk_joint_customer_lot_item_okei1_idx` (`okei_code` ASC) VISIBLE,
    INDEX `fk_joint_customer_lot_item_okato1_idx` (`delivary_region_okato` ASC) VISIBLE,
    CONSTRAINT `fk_joint_customer_lot_item_lot_customer_data1`
        FOREIGN KEY (`lot_customer_data_joint_lot_data_purchase_notice_lot_guid`,
                     `lot_customer_data_joint_lot_data_customer_inn`)
            REFERENCES `zakupki`.`lot_customer_data` (`joint_lot_data_purchase_notice_lot_guid`,
                                                      `joint_lot_data_customer_inn`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_joint_customer_lot_item_okdp1`
        FOREIGN KEY (`okdp_code`)
            REFERENCES `zakupki`.`okdp` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_joint_customer_lot_item_okpd21`
        FOREIGN KEY (`okpd2_code`)
            REFERENCES `zakupki`.`okpd2` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_joint_customer_lot_item_okved1`
        FOREIGN KEY (`okved_code`)
            REFERENCES `zakupki`.`okved` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_joint_customer_lot_item_okved21`
        FOREIGN KEY (`okved2_code`)
            REFERENCES `zakupki`.`okved2` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_joint_customer_lot_item_okei1`
        FOREIGN KEY (`okei_code`)
            REFERENCES `zakupki`.`okei` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_joint_customer_lot_item_okato1`
        FOREIGN KEY (`delivary_region_okato`)
            REFERENCES `zakupki`.`okato` (`code`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`lot_criteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`lot_criteria`
(
    `guid`                     VARCHAR(36)    NOT NULL,
    `purchase_notice_lot_guid` VARCHAR(36)    NOT NULL,
    `name`                     VARCHAR(500)   NOT NULL,
    `description`              VARCHAR(1000)  NULL,
    `max_value`                DECIMAL(22, 2) NOT NULL,
    `weight`                   DECIMAL(22, 2) NOT NULL,
    PRIMARY KEY (`guid`),
    INDEX `fk_lot_criteria_purchase_notice_lot1_idx` (`purchase_notice_lot_guid` ASC) VISIBLE,
    CONSTRAINT `fk_lot_criteria_purchase_notice_lot1`
        FOREIGN KEY (`purchase_notice_lot_guid`)
            REFERENCES `zakupki`.`purchase_notice_lot` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zakupki`.`lot_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zakupki`.`lot_extra`
(
    `purchase_notice_lot_guid` VARCHAR(36)    NOT NULL,
    `integr_code`              VARCHAR(50)    NOT NULL,
    `description`              VARCHAR(200)   NULL,
    `text`                     TEXT(2000)     NULL,
    `number_int`               INT            NULL,
    `number`                   DECIMAL(22, 2) NULL,
    `boolean`                  TINYINT(1)     NULL,
    `datetime`                 DATETIME       NULL,
    `date`                     DATE           NULL,
    `url`                      TEXT(1000)     NULL,
    `nsi_code`                 VARCHAR(20)    NULL,
    `nsi_name`                 VARCHAR(550)   NULL,
    INDEX `fk_lot_extra_purchase_notice_lot1_idx` (`purchase_notice_lot_guid` ASC) VISIBLE,
    PRIMARY KEY (`purchase_notice_lot_guid`, `integr_code`),
    CONSTRAINT `fk_lot_extra_purchase_notice_lot1`
        FOREIGN KEY (`purchase_notice_lot_guid`)
            REFERENCES `zakupki`.`purchase_notice_lot` (`guid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
