SET SQL_SAFE_UPDATES = 0;
DROP TABLE IF EXISTS zakupki.long_term_volume_detail;
DROP TABLE IF EXISTS zakupki.long_term_volumes;
DROP TABLE IF EXISTS zakupki.purchase_plan_item_row;
DROP TABLE IF EXISTS zakupki.innovation_plan_item_row;
DROP TABLE IF EXISTS zakupki.purchase_plan_item;
DROP TABLE IF EXISTS zakupki.innovation_plan_item;
DROP TABLE IF EXISTS zakupki.plan_item;
DROP TABLE IF EXISTS zakupki.purchase_plan;
DROP TABLE IF EXISTS zakupki.customer;
DROP TABLE IF EXISTS zakupki.currency;
DROP TABLE IF EXISTS zakupki.okato;
DROP TABLE IF EXISTS zakupki.okdp;
DROP TABLE IF EXISTS zakupki.okei;
DROP TABLE IF EXISTS zakupki.okopf;
DROP TABLE IF EXISTS zakupki.okpd2;
DROP TABLE IF EXISTS zakupki.okved;
DROP TABLE IF EXISTS zakupki.okved2;
DROP TABLE IF EXISTS zakupki.plan_item_status;
DROP TABLE IF EXISTS zakupki.plan_status;
DROP TABLE IF EXISTS zakupki.purchase_category;
SET SQL_SAFE_UPDATES = 1;