//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.29 at 05:25:54 PM MSK 
//


package ru.homyakin.documentsinfo._223fz.purchase._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Извещение о закупке "Запрос котировок"
 * 
 * <p>Java class for purchaseNoticeZKDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="purchaseNoticeZKDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://zakupki.gov.ru/223fz/purchase/1}purchaseNoticeNonISBaseType">
 *       &lt;sequence>
 *         &lt;element name="quotationExaminationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="quotationExaminationPlace">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="quotationExaminationOrder" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="quotationForm" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="submissionCloseDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="publicationPlannedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="summingupDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="summingupPlace" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "purchaseNoticeZKDataType", propOrder = {
    "quotationExaminationTime",
    "quotationExaminationPlace",
    "quotationExaminationOrder",
    "quotationForm",
    "submissionCloseDateTime",
    "publicationPlannedDate",
    "summingupDate",
    "summingupPlace"
})
public class PurchaseNoticeZKDataType
    extends PurchaseNoticeNonISBaseType
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar quotationExaminationTime;
    @XmlElement(required = true)
    protected String quotationExaminationPlace;
    protected String quotationExaminationOrder;
    protected String quotationForm;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar submissionCloseDateTime;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar publicationPlannedDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar summingupDate;
    protected String summingupPlace;

    /**
     * Gets the value of the quotationExaminationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getQuotationExaminationTime() {
        return quotationExaminationTime;
    }

    /**
     * Sets the value of the quotationExaminationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setQuotationExaminationTime(XMLGregorianCalendar value) {
        this.quotationExaminationTime = value;
    }

    /**
     * Gets the value of the quotationExaminationPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuotationExaminationPlace() {
        return quotationExaminationPlace;
    }

    /**
     * Sets the value of the quotationExaminationPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuotationExaminationPlace(String value) {
        this.quotationExaminationPlace = value;
    }

    /**
     * Gets the value of the quotationExaminationOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuotationExaminationOrder() {
        return quotationExaminationOrder;
    }

    /**
     * Sets the value of the quotationExaminationOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuotationExaminationOrder(String value) {
        this.quotationExaminationOrder = value;
    }

    /**
     * Gets the value of the quotationForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuotationForm() {
        return quotationForm;
    }

    /**
     * Sets the value of the quotationForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuotationForm(String value) {
        this.quotationForm = value;
    }

    /**
     * Gets the value of the submissionCloseDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionCloseDateTime() {
        return submissionCloseDateTime;
    }

    /**
     * Sets the value of the submissionCloseDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionCloseDateTime(XMLGregorianCalendar value) {
        this.submissionCloseDateTime = value;
    }

    /**
     * Gets the value of the publicationPlannedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublicationPlannedDate() {
        return publicationPlannedDate;
    }

    /**
     * Sets the value of the publicationPlannedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublicationPlannedDate(XMLGregorianCalendar value) {
        this.publicationPlannedDate = value;
    }

    /**
     * Gets the value of the summingupDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSummingupDate() {
        return summingupDate;
    }

    /**
     * Sets the value of the summingupDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSummingupDate(XMLGregorianCalendar value) {
        this.summingupDate = value;
    }

    /**
     * Gets the value of the summingupPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummingupPlace() {
        return summingupPlace;
    }

    /**
     * Sets the value of the summingupPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummingupPlace(String value) {
        this.summingupPlace = value;
    }

}
