//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.24 at 08:20:12 PM MSK 
//


package ru.homyakin.zakupki.models._223fz.purchaseplan;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Строка финансового обспечения за счет бюджетных средств
 * 
 * <p>Java class for positionFinancialProvisionVolumeDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="positionFinancialProvisionVolumeDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="targetCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="typeCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="100"/>
 *               &lt;maxInclusive value="999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="contractNum" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;pattern value="\d{19}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="contractEndStageDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="financialVolumePositionRub" type="{http://zakupki.gov.ru/223fz/types/1}money2"/>
 *           &lt;element name="financialVolumePositionRub44" type="{http://zakupki.gov.ru/223fz/types/1}money2"/>
 *           &lt;element name="financialVolumePositionRub44NP" type="{http://zakupki.gov.ru/223fz/types/1}money2"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "positionFinancialProvisionVolumeDataType", propOrder = {
    "targetCode",
    "typeCode",
    "contractNum",
    "contractEndStageDate",
    "financialVolumePositionRub",
    "financialVolumePositionRub44",
    "financialVolumePositionRub44NP"
})
public class PositionFinancialProvisionVolumeDataType {

    protected String targetCode;
    protected Integer typeCode;
    protected String contractNum;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contractEndStageDate;
    protected BigDecimal financialVolumePositionRub;
    protected BigDecimal financialVolumePositionRub44;
    protected BigDecimal financialVolumePositionRub44NP;

    /**
     * Gets the value of the targetCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetCode() {
        return targetCode;
    }

    /**
     * Sets the value of the targetCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetCode(String value) {
        this.targetCode = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTypeCode(Integer value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the contractNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNum() {
        return contractNum;
    }

    /**
     * Sets the value of the contractNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNum(String value) {
        this.contractNum = value;
    }

    /**
     * Gets the value of the contractEndStageDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractEndStageDate() {
        return contractEndStageDate;
    }

    /**
     * Sets the value of the contractEndStageDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractEndStageDate(XMLGregorianCalendar value) {
        this.contractEndStageDate = value;
    }

    /**
     * Gets the value of the financialVolumePositionRub property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFinancialVolumePositionRub() {
        return financialVolumePositionRub;
    }

    /**
     * Sets the value of the financialVolumePositionRub property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFinancialVolumePositionRub(BigDecimal value) {
        this.financialVolumePositionRub = value;
    }

    /**
     * Gets the value of the financialVolumePositionRub44 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFinancialVolumePositionRub44() {
        return financialVolumePositionRub44;
    }

    /**
     * Sets the value of the financialVolumePositionRub44 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFinancialVolumePositionRub44(BigDecimal value) {
        this.financialVolumePositionRub44 = value;
    }

    /**
     * Gets the value of the financialVolumePositionRub44NP property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFinancialVolumePositionRub44NP() {
        return financialVolumePositionRub44NP;
    }

    /**
     * Sets the value of the financialVolumePositionRub44NP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFinancialVolumePositionRub44NP(BigDecimal value) {
        this.financialVolumePositionRub44NP = value;
    }

}
