SET SQL_SAFE_UPDATES = 0;
DROP TABLE zakupki.long_term_volume_detail;
DROP TABLE zakupki.long_term_volumes;
DROP TABLE zakupki.purchase_plan_item_row;
DROP TABLE zakupki.innovation_plan_item_row;
DROP TABLE zakupki.purchase_plan_item;
DROP TABLE zakupki.innovation_plan_item;
DROP TABLE zakupki.plan_item;
DROP TABLE zakupki.purchase_plan;
DROP TABLE zakupki.customer;
DROP TABLE zakupki.currency;
DROP TABLE zakupki.okdp;
DROP TABLE zakupki.okei;
DROP TABLE zakupki.okopf;
DROP TABLE zakupki.okpd2;
DROP TABLE zakupki.okved;
DROP TABLE zakupki.okved2;
DROP TABLE zakupki.plan_item_status;
DROP TABLE zakupki.plan_status;
DROP TABLE zakupki.purchase_category;
SET SQL_SAFE_UPDATES = 1;