//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.29 at 05:25:54 PM MSK 
//


package ru.homyakin.zakupki.documentsinfo._223fz.contract;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.homyakin.zakupki.documentsinfo._223fz.types.CurrencyType;
import ru.homyakin.zakupki.documentsinfo._223fz.types.CustomerInfoType;
import ru.homyakin.zakupki.documentsinfo._223fz.types.DocumentListType;
import ru.homyakin.zakupki.documentsinfo._223fz.types.ElectronicPlaceInfoType;
import ru.homyakin.zakupki.documentsinfo._223fz.types.PlanInfoType;


/**
 * Сведения о договоре
 * 
 * <p>Java class for contractDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contractDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="guid" type="{http://zakupki.gov.ru/223fz/types/1}guidType"/>
 *         &lt;element name="registrationNumber" type="{http://zakupki.gov.ru/223fz/types/1}registrationNumber23Type" minOccurs="0"/>
 *         &lt;element name="notice44" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="noticeNotPlacedByFz223p5s4" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="notice44Num" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lot44Num" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="termination" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="extension" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="prolongation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="customerAppealedOrNeedsApproval" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="customerApprovalOrAntimonopolyDescisionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="startExecutionTerm" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="endExecutionTerm" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lotNum" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="planPosition" type="{http://zakupki.gov.ru/223fz/types/1}planInfoType" minOccurs="0"/>
 *         &lt;element name="urlEIS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="3000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="urlVSRZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="3000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="urlKisRmis" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="3000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="createDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="customer" type="{http://zakupki.gov.ru/223fz/types/1}customerInfoType"/>
 *         &lt;element name="placer" type="{http://zakupki.gov.ru/223fz/types/1}customerInfoType"/>
 *         &lt;element name="detachedOrg" type="{http://zakupki.gov.ru/223fz/types/1}customerInfoType" minOccurs="0"/>
 *         &lt;element name="publicationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="status" type="{http://zakupki.gov.ru/223fz/contract/1}contractStatusType" minOccurs="0"/>
 *         &lt;element name="version" type="{http://zakupki.gov.ru/223fz/types/1}versionType" minOccurs="0"/>
 *         &lt;element name="modificationDescription" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="digitalPurchase" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="digitalPurchaseCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="provider" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="providerCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="changeContract" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="attachments" type="{http://zakupki.gov.ru/223fz/types/1}documentListType" minOccurs="0"/>
 *         &lt;element name="contractRegNumber" type="{http://zakupki.gov.ru/223fz/types/1}registrationNumber23Type" minOccurs="0"/>
 *         &lt;element name="name" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="contractDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="approveDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="purchaseNoticeInfo" type="{http://zakupki.gov.ru/223fz/contract/1}purchaseNoticeInfoType" minOccurs="0"/>
 *         &lt;element name="lotGuid" type="{http://zakupki.gov.ru/223fz/types/1}guidType" minOccurs="0"/>
 *         &lt;element name="subjectContract">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="purchaseTypeInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="code">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *                         &lt;maxLength value="5"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="name" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *                         &lt;maxLength value="500"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="resumeDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="supplierInfo" type="{http://zakupki.gov.ru/223fz/contract/1}supplierMainType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hasSubcontractor" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasSubcontractorCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="subcontractorsTotal" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="hasGoodInfo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="additionalInfo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="price" type="{http://zakupki.gov.ru/223fz/types/1}unsignedMoney2"/>
 *         &lt;element name="exchangeRate" type="{http://zakupki.gov.ru/223fz/types/1}money6" minOccurs="0"/>
 *         &lt;element name="exchangeRateDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="rubPrice" type="{http://zakupki.gov.ru/223fz/types/1}money2" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://zakupki.gov.ru/223fz/types/1}currencyType"/>
 *         &lt;element name="startExecutionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="endExecutionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="contractPositions" type="{http://zakupki.gov.ru/223fz/contract/1}positionListType" minOccurs="0"/>
 *         &lt;element name="contractChangeDocs" type="{http://zakupki.gov.ru/223fz/contract/1}contractDocListType" minOccurs="0"/>
 *         &lt;element name="contractConfirmingDocs" type="{http://zakupki.gov.ru/223fz/contract/1}contractDocListType" minOccurs="0"/>
 *         &lt;element name="hasOkpdAndOkdpRows" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasOkpd2Rows" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isElectronicPlace" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="electronicPlaceInfo" type="{http://zakupki.gov.ru/223fz/types/1}electronicPlaceInfoType" minOccurs="0"/>
 *         &lt;element name="electorincPlacePublishDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contractDataType", propOrder = {
    "guid",
    "registrationNumber",
    "notice44",
    "noticeNotPlacedByFz223P5S4",
    "notice44Num",
    "lot44Num",
    "termination",
    "extension",
    "prolongation",
    "customerAppealedOrNeedsApproval",
    "customerApprovalOrAntimonopolyDescisionDate",
    "startExecutionTerm",
    "endExecutionTerm",
    "lotNum",
    "planPosition",
    "urlEIS",
    "urlVSRZ",
    "urlKisRmis",
    "createDateTime",
    "customer",
    "placer",
    "detachedOrg",
    "publicationDate",
    "status",
    "version",
    "modificationDescription",
    "digitalPurchase",
    "digitalPurchaseCode",
    "provider",
    "providerCode",
    "changeContract",
    "attachments",
    "contractRegNumber",
    "name",
    "contractDate",
    "approveDate",
    "purchaseNoticeInfo",
    "lotGuid",
    "subjectContract",
    "purchaseTypeInfo",
    "resumeDate",
    "supplierInfo",
    "hasSubcontractor",
    "hasSubcontractorCode",
    "subcontractorsTotal",
    "hasGoodInfo",
    "additionalInfo",
    "price",
    "exchangeRate",
    "exchangeRateDate",
    "rubPrice",
    "currency",
    "startExecutionDate",
    "endExecutionDate",
    "contractPositions",
    "contractChangeDocs",
    "contractConfirmingDocs",
    "hasOkpdAndOkdpRows",
    "hasOkpd2Rows",
    "isElectronicPlace",
    "electronicPlaceInfo",
    "electorincPlacePublishDate"
})
public class ContractDataType {

    @XmlElement(required = true)
    protected String guid;
    protected String registrationNumber;
    protected Boolean notice44;
    @XmlElement(name = "noticeNotPlacedByFz223p5s4")
    protected Boolean noticeNotPlacedByFz223P5S4;
    protected String notice44Num;
    protected String lot44Num;
    protected boolean termination;
    protected boolean extension;
    protected boolean prolongation;
    protected Boolean customerAppealedOrNeedsApproval;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar customerApprovalOrAntimonopolyDescisionDate;
    protected String startExecutionTerm;
    protected String endExecutionTerm;
    protected Long lotNum;
    protected PlanInfoType planPosition;
    protected String urlEIS;
    protected String urlVSRZ;
    protected String urlKisRmis;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createDateTime;
    @XmlElement(required = true)
    protected CustomerInfoType customer;
    @XmlElement(required = true)
    protected CustomerInfoType placer;
    protected CustomerInfoType detachedOrg;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar publicationDate;
    @XmlSchemaType(name = "string")
    protected ContractStatusType status;
    protected Long version;
    protected String modificationDescription;
    protected boolean digitalPurchase;
    @XmlElement(required = true)
    protected String digitalPurchaseCode;
    protected boolean provider;
    protected String providerCode;
    protected boolean changeContract;
    protected DocumentListType attachments;
    protected String contractRegNumber;
    protected String name;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contractDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar approveDate;
    protected PurchaseNoticeInfoType purchaseNoticeInfo;
    protected String lotGuid;
    @XmlElement(required = true)
    protected String subjectContract;
    @XmlElement(required = true)
    protected ContractDataType.PurchaseTypeInfo purchaseTypeInfo;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar resumeDate;
    protected List<SupplierMainType> supplierInfo;
    protected Boolean hasSubcontractor;
    protected String hasSubcontractorCode;
    protected String subcontractorsTotal;
    protected Boolean hasGoodInfo;
    protected String additionalInfo;
    @XmlElement(required = true)
    protected BigDecimal price;
    protected BigDecimal exchangeRate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar exchangeRateDate;
    protected BigDecimal rubPrice;
    @XmlElement(required = true)
    protected CurrencyType currency;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startExecutionDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endExecutionDate;
    protected PositionListType contractPositions;
    protected ContractDocListType contractChangeDocs;
    protected ContractDocListType contractConfirmingDocs;
    protected Boolean hasOkpdAndOkdpRows;
    protected Boolean hasOkpd2Rows;
    protected Boolean isElectronicPlace;
    protected ElectronicPlaceInfoType electronicPlaceInfo;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar electorincPlacePublishDate;

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the registrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * Sets the value of the registrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNumber(String value) {
        this.registrationNumber = value;
    }

    /**
     * Gets the value of the notice44 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNotice44() {
        return notice44;
    }

    /**
     * Sets the value of the notice44 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNotice44(Boolean value) {
        this.notice44 = value;
    }

    /**
     * Gets the value of the noticeNotPlacedByFz223P5S4 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoticeNotPlacedByFz223P5S4() {
        return noticeNotPlacedByFz223P5S4;
    }

    /**
     * Sets the value of the noticeNotPlacedByFz223P5S4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoticeNotPlacedByFz223P5S4(Boolean value) {
        this.noticeNotPlacedByFz223P5S4 = value;
    }

    /**
     * Gets the value of the notice44Num property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotice44Num() {
        return notice44Num;
    }

    /**
     * Sets the value of the notice44Num property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotice44Num(String value) {
        this.notice44Num = value;
    }

    /**
     * Gets the value of the lot44Num property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLot44Num() {
        return lot44Num;
    }

    /**
     * Sets the value of the lot44Num property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLot44Num(String value) {
        this.lot44Num = value;
    }

    /**
     * Gets the value of the termination property.
     * 
     */
    public boolean isTermination() {
        return termination;
    }

    /**
     * Sets the value of the termination property.
     * 
     */
    public void setTermination(boolean value) {
        this.termination = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     */
    public boolean isExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     */
    public void setExtension(boolean value) {
        this.extension = value;
    }

    /**
     * Gets the value of the prolongation property.
     * 
     */
    public boolean isProlongation() {
        return prolongation;
    }

    /**
     * Sets the value of the prolongation property.
     * 
     */
    public void setProlongation(boolean value) {
        this.prolongation = value;
    }

    /**
     * Gets the value of the customerAppealedOrNeedsApproval property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCustomerAppealedOrNeedsApproval() {
        return customerAppealedOrNeedsApproval;
    }

    /**
     * Sets the value of the customerAppealedOrNeedsApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCustomerAppealedOrNeedsApproval(Boolean value) {
        this.customerAppealedOrNeedsApproval = value;
    }

    /**
     * Gets the value of the customerApprovalOrAntimonopolyDescisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCustomerApprovalOrAntimonopolyDescisionDate() {
        return customerApprovalOrAntimonopolyDescisionDate;
    }

    /**
     * Sets the value of the customerApprovalOrAntimonopolyDescisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCustomerApprovalOrAntimonopolyDescisionDate(XMLGregorianCalendar value) {
        this.customerApprovalOrAntimonopolyDescisionDate = value;
    }

    /**
     * Gets the value of the startExecutionTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartExecutionTerm() {
        return startExecutionTerm;
    }

    /**
     * Sets the value of the startExecutionTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartExecutionTerm(String value) {
        this.startExecutionTerm = value;
    }

    /**
     * Gets the value of the endExecutionTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndExecutionTerm() {
        return endExecutionTerm;
    }

    /**
     * Sets the value of the endExecutionTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndExecutionTerm(String value) {
        this.endExecutionTerm = value;
    }

    /**
     * Gets the value of the lotNum property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLotNum() {
        return lotNum;
    }

    /**
     * Sets the value of the lotNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLotNum(Long value) {
        this.lotNum = value;
    }

    /**
     * Gets the value of the planPosition property.
     * 
     * @return
     *     possible object is
     *     {@link PlanInfoType }
     *     
     */
    public PlanInfoType getPlanPosition() {
        return planPosition;
    }

    /**
     * Sets the value of the planPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanInfoType }
     *     
     */
    public void setPlanPosition(PlanInfoType value) {
        this.planPosition = value;
    }

    /**
     * Gets the value of the urlEIS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlEIS() {
        return urlEIS;
    }

    /**
     * Sets the value of the urlEIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlEIS(String value) {
        this.urlEIS = value;
    }

    /**
     * Gets the value of the urlVSRZ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlVSRZ() {
        return urlVSRZ;
    }

    /**
     * Sets the value of the urlVSRZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlVSRZ(String value) {
        this.urlVSRZ = value;
    }

    /**
     * Gets the value of the urlKisRmis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlKisRmis() {
        return urlKisRmis;
    }

    /**
     * Sets the value of the urlKisRmis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlKisRmis(String value) {
        this.urlKisRmis = value;
    }

    /**
     * Gets the value of the createDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDateTime() {
        return createDateTime;
    }

    /**
     * Sets the value of the createDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDateTime(XMLGregorianCalendar value) {
        this.createDateTime = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerInfoType }
     *     
     */
    public CustomerInfoType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerInfoType }
     *     
     */
    public void setCustomer(CustomerInfoType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the placer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerInfoType }
     *     
     */
    public CustomerInfoType getPlacer() {
        return placer;
    }

    /**
     * Sets the value of the placer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerInfoType }
     *     
     */
    public void setPlacer(CustomerInfoType value) {
        this.placer = value;
    }

    /**
     * Gets the value of the detachedOrg property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerInfoType }
     *     
     */
    public CustomerInfoType getDetachedOrg() {
        return detachedOrg;
    }

    /**
     * Sets the value of the detachedOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerInfoType }
     *     
     */
    public void setDetachedOrg(CustomerInfoType value) {
        this.detachedOrg = value;
    }

    /**
     * Gets the value of the publicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPublicationDate() {
        return publicationDate;
    }

    /**
     * Sets the value of the publicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublicationDate(XMLGregorianCalendar value) {
        this.publicationDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ContractStatusType }
     *     
     */
    public ContractStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractStatusType }
     *     
     */
    public void setStatus(ContractStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVersion(Long value) {
        this.version = value;
    }

    /**
     * Gets the value of the modificationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationDescription() {
        return modificationDescription;
    }

    /**
     * Sets the value of the modificationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationDescription(String value) {
        this.modificationDescription = value;
    }

    /**
     * Gets the value of the digitalPurchase property.
     * 
     */
    public boolean isDigitalPurchase() {
        return digitalPurchase;
    }

    /**
     * Sets the value of the digitalPurchase property.
     * 
     */
    public void setDigitalPurchase(boolean value) {
        this.digitalPurchase = value;
    }

    /**
     * Gets the value of the digitalPurchaseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigitalPurchaseCode() {
        return digitalPurchaseCode;
    }

    /**
     * Sets the value of the digitalPurchaseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigitalPurchaseCode(String value) {
        this.digitalPurchaseCode = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     */
    public boolean isProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     */
    public void setProvider(boolean value) {
        this.provider = value;
    }

    /**
     * Gets the value of the providerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderCode() {
        return providerCode;
    }

    /**
     * Sets the value of the providerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderCode(String value) {
        this.providerCode = value;
    }

    /**
     * Gets the value of the changeContract property.
     * 
     */
    public boolean isChangeContract() {
        return changeContract;
    }

    /**
     * Sets the value of the changeContract property.
     * 
     */
    public void setChangeContract(boolean value) {
        this.changeContract = value;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentListType }
     *     
     */
    public DocumentListType getAttachments() {
        return attachments;
    }

    /**
     * Sets the value of the attachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentListType }
     *     
     */
    public void setAttachments(DocumentListType value) {
        this.attachments = value;
    }

    /**
     * Gets the value of the contractRegNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractRegNumber() {
        return contractRegNumber;
    }

    /**
     * Sets the value of the contractRegNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractRegNumber(String value) {
        this.contractRegNumber = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the contractDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractDate() {
        return contractDate;
    }

    /**
     * Sets the value of the contractDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractDate(XMLGregorianCalendar value) {
        this.contractDate = value;
    }

    /**
     * Gets the value of the approveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApproveDate() {
        return approveDate;
    }

    /**
     * Sets the value of the approveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApproveDate(XMLGregorianCalendar value) {
        this.approveDate = value;
    }

    /**
     * Gets the value of the purchaseNoticeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseNoticeInfoType }
     *     
     */
    public PurchaseNoticeInfoType getPurchaseNoticeInfo() {
        return purchaseNoticeInfo;
    }

    /**
     * Sets the value of the purchaseNoticeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseNoticeInfoType }
     *     
     */
    public void setPurchaseNoticeInfo(PurchaseNoticeInfoType value) {
        this.purchaseNoticeInfo = value;
    }

    /**
     * Gets the value of the lotGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotGuid() {
        return lotGuid;
    }

    /**
     * Sets the value of the lotGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotGuid(String value) {
        this.lotGuid = value;
    }

    /**
     * Gets the value of the subjectContract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectContract() {
        return subjectContract;
    }

    /**
     * Sets the value of the subjectContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectContract(String value) {
        this.subjectContract = value;
    }

    /**
     * Gets the value of the purchaseTypeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContractDataType.PurchaseTypeInfo }
     *     
     */
    public ContractDataType.PurchaseTypeInfo getPurchaseTypeInfo() {
        return purchaseTypeInfo;
    }

    /**
     * Sets the value of the purchaseTypeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractDataType.PurchaseTypeInfo }
     *     
     */
    public void setPurchaseTypeInfo(ContractDataType.PurchaseTypeInfo value) {
        this.purchaseTypeInfo = value;
    }

    /**
     * Gets the value of the resumeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getResumeDate() {
        return resumeDate;
    }

    /**
     * Sets the value of the resumeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setResumeDate(XMLGregorianCalendar value) {
        this.resumeDate = value;
    }

    /**
     * Gets the value of the supplierInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supplierInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupplierInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplierMainType }
     * 
     * 
     */
    public List<SupplierMainType> getSupplierInfo() {
        if (supplierInfo == null) {
            supplierInfo = new ArrayList<SupplierMainType>();
        }
        return this.supplierInfo;
    }

    /**
     * Gets the value of the hasSubcontractor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasSubcontractor() {
        return hasSubcontractor;
    }

    /**
     * Sets the value of the hasSubcontractor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasSubcontractor(Boolean value) {
        this.hasSubcontractor = value;
    }

    /**
     * Gets the value of the hasSubcontractorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasSubcontractorCode() {
        return hasSubcontractorCode;
    }

    /**
     * Sets the value of the hasSubcontractorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasSubcontractorCode(String value) {
        this.hasSubcontractorCode = value;
    }

    /**
     * Gets the value of the subcontractorsTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubcontractorsTotal() {
        return subcontractorsTotal;
    }

    /**
     * Sets the value of the subcontractorsTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubcontractorsTotal(String value) {
        this.subcontractorsTotal = value;
    }

    /**
     * Gets the value of the hasGoodInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasGoodInfo() {
        return hasGoodInfo;
    }

    /**
     * Sets the value of the hasGoodInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasGoodInfo(Boolean value) {
        this.hasGoodInfo = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInfo(String value) {
        this.additionalInfo = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the exchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExchangeRate() {
        return exchangeRate;
    }

    /**
     * Sets the value of the exchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExchangeRate(BigDecimal value) {
        this.exchangeRate = value;
    }

    /**
     * Gets the value of the exchangeRateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExchangeRateDate() {
        return exchangeRateDate;
    }

    /**
     * Sets the value of the exchangeRateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExchangeRateDate(XMLGregorianCalendar value) {
        this.exchangeRateDate = value;
    }

    /**
     * Gets the value of the rubPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRubPrice() {
        return rubPrice;
    }

    /**
     * Sets the value of the rubPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRubPrice(BigDecimal value) {
        this.rubPrice = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyType }
     *     
     */
    public CurrencyType getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyType }
     *     
     */
    public void setCurrency(CurrencyType value) {
        this.currency = value;
    }

    /**
     * Gets the value of the startExecutionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartExecutionDate() {
        return startExecutionDate;
    }

    /**
     * Sets the value of the startExecutionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartExecutionDate(XMLGregorianCalendar value) {
        this.startExecutionDate = value;
    }

    /**
     * Gets the value of the endExecutionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndExecutionDate() {
        return endExecutionDate;
    }

    /**
     * Sets the value of the endExecutionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndExecutionDate(XMLGregorianCalendar value) {
        this.endExecutionDate = value;
    }

    /**
     * Gets the value of the contractPositions property.
     * 
     * @return
     *     possible object is
     *     {@link PositionListType }
     *     
     */
    public PositionListType getContractPositions() {
        return contractPositions;
    }

    /**
     * Sets the value of the contractPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionListType }
     *     
     */
    public void setContractPositions(PositionListType value) {
        this.contractPositions = value;
    }

    /**
     * Gets the value of the contractChangeDocs property.
     * 
     * @return
     *     possible object is
     *     {@link ContractDocListType }
     *     
     */
    public ContractDocListType getContractChangeDocs() {
        return contractChangeDocs;
    }

    /**
     * Sets the value of the contractChangeDocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractDocListType }
     *     
     */
    public void setContractChangeDocs(ContractDocListType value) {
        this.contractChangeDocs = value;
    }

    /**
     * Gets the value of the contractConfirmingDocs property.
     * 
     * @return
     *     possible object is
     *     {@link ContractDocListType }
     *     
     */
    public ContractDocListType getContractConfirmingDocs() {
        return contractConfirmingDocs;
    }

    /**
     * Sets the value of the contractConfirmingDocs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractDocListType }
     *     
     */
    public void setContractConfirmingDocs(ContractDocListType value) {
        this.contractConfirmingDocs = value;
    }

    /**
     * Gets the value of the hasOkpdAndOkdpRows property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasOkpdAndOkdpRows() {
        return hasOkpdAndOkdpRows;
    }

    /**
     * Sets the value of the hasOkpdAndOkdpRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasOkpdAndOkdpRows(Boolean value) {
        this.hasOkpdAndOkdpRows = value;
    }

    /**
     * Gets the value of the hasOkpd2Rows property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasOkpd2Rows() {
        return hasOkpd2Rows;
    }

    /**
     * Sets the value of the hasOkpd2Rows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasOkpd2Rows(Boolean value) {
        this.hasOkpd2Rows = value;
    }

    /**
     * Gets the value of the isElectronicPlace property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsElectronicPlace() {
        return isElectronicPlace;
    }

    /**
     * Sets the value of the isElectronicPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsElectronicPlace(Boolean value) {
        this.isElectronicPlace = value;
    }

    /**
     * Gets the value of the electronicPlaceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ElectronicPlaceInfoType }
     *     
     */
    public ElectronicPlaceInfoType getElectronicPlaceInfo() {
        return electronicPlaceInfo;
    }

    /**
     * Sets the value of the electronicPlaceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectronicPlaceInfoType }
     *     
     */
    public void setElectronicPlaceInfo(ElectronicPlaceInfoType value) {
        this.electronicPlaceInfo = value;
    }

    /**
     * Gets the value of the electorincPlacePublishDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getElectorincPlacePublishDate() {
        return electorincPlacePublishDate;
    }

    /**
     * Sets the value of the electorincPlacePublishDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setElectorincPlacePublishDate(XMLGregorianCalendar value) {
        this.electorincPlacePublishDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="code">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
     *               &lt;maxLength value="5"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="name" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://zakupki.gov.ru/223fz/types/1}nonEmptyString">
     *               &lt;maxLength value="500"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "code",
        "name"
    })
    public static class PurchaseTypeInfo {

        @XmlElement(required = true)
        protected String code;
        protected String name;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
