//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.29 at 05:25:54 PM MSK 
//


package ru.homyakin.zakupki.documentsinfo._223fz.contract;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ru.homyakin.zakupki.documentsinfo._223fz.types.ItemType;


/**
 * Данные позиции в пакете
 * 
 * <p>Java class for electronicContractItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="electronicContractItemType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://zakupki.gov.ru/223fz/types/1}itemType">
 *       &lt;sequence>
 *         &lt;element name="electronicContractInfoData" type="{http://zakupki.gov.ru/223fz/contract/1}electronicContractDataType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "electronicContractItemType", propOrder = {
    "electronicContractInfoData"
})
public class ElectronicContractItemType
    extends ItemType
{

    @XmlElement(required = true)
    protected ElectronicContractDataType electronicContractInfoData;

    /**
     * Gets the value of the electronicContractInfoData property.
     * 
     * @return
     *     possible object is
     *     {@link ElectronicContractDataType }
     *     
     */
    public ElectronicContractDataType getElectronicContractInfoData() {
        return electronicContractInfoData;
    }

    /**
     * Sets the value of the electronicContractInfoData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectronicContractDataType }
     *     
     */
    public void setElectronicContractInfoData(ElectronicContractDataType value) {
        this.electronicContractInfoData = value;
    }

}
